function generateInteger(int) {
    return Math.floor(Math.random() * int);
}

function generateOneDecimalUnder5() {
    let randomNumber = Math.random() * 5;
    return Math.round(randomNumber * 10) / 10;
}

export const products = {
    shoe: [
        {
            id: 1,
            name: 'Khapara Black Shoe',
            brand: "Khapara",
            tagline: 'Elegance in every step.',
            price: generateInteger(10000),
            reviewCount: generateInteger(10000),
            averageRating: generateOneDecimalUnder5(),
            images: [
                { id: 1, href: "/shoe/blackshoe/shoe (1).png", alt: 'AngledView' },
                { id: 2, href: "/shoe/blackshoe/shoe (2).png", alt: 'BackView' },
                { id: 3, href: "/shoe/blackshoe/shoe (3).png", alt: 'FrntView' },
                { id: 4, href: "/shoe/blackshoe/shoe (4).png", alt: 'LeftSideView' },
                { id: 5, href: "/shoe/blackshoe/shoe (5).png", alt: 'RightSideView' },
            ],
            color: { id: 1, name: 'Black', hex: 'bg-black', selected: true },
            sizes: [
                { label: '5 (24.1cm)', value: 's5', selected: true },
                { label: '6 (24.8cm)', value: 's6' },
                { label: '7 (25.7cm)', value: 's7' },
                { label: '8 (26.5cm)', value: 's8' },
                { label: '9 (27.3cm)', value: 's9' },
                { label: '10 (28.1cm)', value: 's10' },
            ],
        },
        {
            id: 2,
            name: 'Khapara Blue Shoe',
            brand: "Khapara",
            tagline: 'Confidence crafted in every shoe.',
            price: generateInteger(10000),
            reviewCount: generateInteger(100000),
            averageRating: generateOneDecimalUnder5(),
            images: [
                { id: 1, href: "/shoe/blueshoe/shoe (1).png", alt: 'AngledView' },
                { id: 2, href: "/shoe/blueshoe/shoe (2).png", alt: 'BackView' },
                { id: 3, href: "/shoe/blueshoe/shoe (3).png", alt: 'FrntView' },
                { id: 4, href: "/shoe/blueshoe/shoe (4).png", alt: 'LeftSideView' },
                { id: 5, href: "/shoe/blueshoe/shoe (5).png", alt: 'RightSideView' },
            ],
            color: { id: 2, name: 'Blue', hex: 'bg-[#1C518F]', selected: false },
            sizes: [
                { label: '5 (24.1cm)', value: 's5', selected: true },
                { label: '6 (24.8cm)', value: 's6' },
                { label: '7 (25.7cm)', value: 's7' },
                { label: '8 (26.5cm)', value: 's8' },
                { label: '9 (27.3cm)', value: 's9' },
                { label: '10 (28.1cm)', value: 's10' },
            ],
        },
        {
            id: 3,
            name: 'Khapara Classic Bold Brown Shoe',
            brand: "Khapara",
            tagline: 'Timeless style, modern stride.',
            price: generateInteger(10000),
            reviewCount: generateInteger(100000),
            averageRating: generateOneDecimalUnder5(),
            images: [
                { id: 1, href: "/shoe/classic-bold-brown/shoe (1).png", alt: 'AngledView' },
                { id: 2, href: "/shoe/classic-bold-brown/shoe (2).png", alt: 'BackView' },
                { id: 3, href: "/shoe/classic-bold-brown/shoe (3).png", alt: 'FrntView' },
                { id: 4, href: "/shoe/classic-bold-brown/shoe (4).png", alt: 'LeftSideView' },
                { id: 5, href: "/shoe/classic-bold-brown/shoe (5).png", alt: 'RightSideView' },
            ],
            color: { id: 3, name: 'Bold Brown', hex: 'bg-[#5B3F34]', selected: false },
            sizes: [
                { label: '5 (24.1cm)', value: 's5', selected: true },
                { label: '6 (24.8cm)', value: 's6' },
                { label: '7 (25.7cm)', value: 's7' },
                { label: '8 (26.5cm)', value: 's8' },
                { label: '9 (27.3cm)', value: 's9' },
                { label: '10 (28.1cm)', value: 's10' },
            ],
        },
        {
            id: 4,
            name: 'Khapara Classic Brown Shoe',
            brand: "Khapara",
            tagline: 'Walk bold, walk classic.',
            price: generateInteger(10000),
            reviewCount: generateInteger(100000),
            averageRating: generateOneDecimalUnder5(),
            images: [
                { id: 1, href: "/shoe/classic-brown/shoe (1).png", alt: 'AngledView' },
                { id: 2, href: "/shoe/classic-brown/shoe (2).png", alt: 'BackView' },
                { id: 3, href: "/shoe/classic-brown/shoe (3).png", alt: 'FrntView' },
                { id: 4, href: "/shoe/classic-brown/shoe (4).png", alt: 'LeftSideView' },
                { id: 5, href: "/shoe/classic-brown/shoe (5).png", alt: 'RightSideView' },
            ],
            color: { id: 4, name: 'Classic Brown', hex: 'bg-[#B07A68]', selected: false },
            sizes: [
                { label: '5 (24.1cm)', value: 's5', selected: true },
                { label: '6 (24.8cm)', value: 's6' },
                { label: '7 (25.7cm)', value: 's7' },
                { label: '8 (26.5cm)', value: 's8' },
                { label: '9 (27.3cm)', value: 's9' },
                { label: '10 (28.1cm)', value: 's10' },
            ],
        },
        {
            id: 5,
            name: 'Khapara White Shoe',
            brand: "Khapara",
            tagline: 'Sophistication from heel to toe.',
            price: generateInteger(10000),
            reviewCount: generateInteger(100000),
            averageRating: generateOneDecimalUnder5(),
            images: [
                { id: 1, href: "/shoe/whiteshoe/shoe (1).png", alt: 'AngledView' },
                { id: 2, href: "/shoe/whiteshoe/shoe (2).png", alt: 'BackView' },
                { id: 3, href: "/shoe/whiteshoe/shoe (3).png", alt: 'FrntView' },
                { id: 4, href: "/shoe/whiteshoe/shoe (4).png", alt: 'LeftSideView' },
                { id: 5, href: "/shoe/whiteshoe/shoe (5).png", alt: 'RightSideView' },
            ],
            color: { id: 5, name: 'White', hex: 'bg-white', selected: false },
            sizes: [
                { label: '5 (24.1cm)', value: 's5', selected: true },
                { label: '6 (24.8cm)', value: 's6' },
                { label: '7 (25.7cm)', value: 's7' },
                { label: '8 (26.5cm)', value: 's8' },
                { label: '9 (27.3cm)', value: 's9' },
                { label: '10 (28.1cm)', value: 's10' },
            ],
        },
        {
            id: 6,
            name: 'Khapara Red Shoe',
            brand: "Khapara",
            tagline: 'The power of the shoe, perfected.',
            price: generateInteger(10000),
            reviewCount: generateInteger(100000),
            averageRating: generateOneDecimalUnder5(),
            images: [
                { id: 1, href: "/shoe/redshoe/shoe (1).png", alt: 'AngledView' },
                { id: 2, href: "/shoe/redshoe/shoe (2).png", alt: 'BackView' },
                { id: 3, href: "/shoe/redshoe/shoe (3).png", alt: 'FrntView' },
                { id: 4, href: "/shoe/redshoe/shoe (4).png", alt: 'LeftSideView' },
                { id: 5, href: "/shoe/redshoe/shoe (5).png", alt: 'RightSideView' },
            ],
            color: { id: 6, name: 'Red', hex: 'bg-[#F05554]', selected: false },
            sizes: [
                { label: '5 (24.1cm)', value: 's5', selected: true },
                { label: '6 (24.8cm)', value: 's6' },
                { label: '7 (25.7cm)', value: 's7' },
                { label: '8 (26.5cm)', value: 's8' },
                { label: '9 (27.3cm)', value: 's9' },
                { label: '10 (28.1cm)', value: 's10' },
            ],
        },
    ],
    otherProducts: [
        {
            id: 7,
            name: 'Premium Watch',
            brand: "Premium",
            tagline: 'Crafted for those who lead.',
            price: generateInteger(10000),
            reviewCount: generateInteger(100000),
            averageRating: generateOneDecimalUnder5(),
            images: [
                { id: 1, href: "/watch/watch (1).png", alt: 'AngledView' },
                { id: 2, href: "/watch/watch (2).png", alt: 'FrontView' },
                { id: 3, href: "/watch/watch (3).png", alt: 'RightSide' },
            ],
            color: { id: 7, name: 'Sliver', hex: 'bg-[#C0C0C0]', selected: false },
            sizes: [
                { label: 'Small (160mm)', value: 'small' },
                { label: 'Medium (180mm)', value: 'medium', selected: true },
                { label: 'Large (200mm)', value: 'large' },
            ],
        },
        {
            id: 8,
            name: 'Impex Battery Fan',
            brand: "Impex",
            tagline: 'Cool comfort, anywhere you go.',
            price: generateInteger(10000),
            reviewCount: generateInteger(100000),
            averageRating: generateOneDecimalUnder5(),
            images: [
                { id: 1, href: "/fan/batteryBlueFan/batteryFan (1).png", alt: 'FrontView' },
                { id: 2, href: "/fan/batteryBlueFan/batteryFan (2).png", alt: 'OtherView' },
                { id: 3, href: "/fan/batteryBlueFan/batteryFan (3).png", alt: 'OtherView' },
            ],
            color: { id: 8, name: 'Grey', hex: 'bg-[#8D8D8D]', selected: false },
            sizes: [],
        },
        {
            id: 9,
            name: 'Tanco Premium Ladies Purse',
            brand: "Tanco",
            tagline: 'Carry elegance, carry yourself.',
            price: generateInteger(10000),
            reviewCount: generateInteger(100000),
            averageRating: generateOneDecimalUnder5(),
            images: [
                { id: 1, href: "/ladiesPurse/ladiesPurse (1).jpg", alt: 'FrontView' },
                { id: 2, href: "/ladiesPurse/ladiesPurse (2).jpg", alt: 'OtherView' },
                { id: 3, href: "/ladiesPurse/ladiesPurse (3).jpg", alt: 'OtherView' },
                { id: 4, href: "/ladiesPurse/ladiesPurse (4).jpg", alt: 'OtherView' },
            ],
            color: { id: 9, name: 'Grey', hex: 'bg-[#F4EEF0]', selected: false },
            sizes: [],
        },
    ],
    neckband: [
        {
            id: 10,
            name: 'Kammee Black Neckband',
            brand: "Kammee",
            tagline: 'Style meets sound.',
            price: generateInteger(10000),
            reviewCount: generateInteger(100000),
            averageRating: generateOneDecimalUnder5(),
            images: [
                { id: 1, href: "/nechband/blackNeckband/nechbandBlack (1).jpg", alt: 'FrontView' },
                { id: 2, href: "/nechband/nechband (1).jpg", alt: 'OtherView' },
                { id: 3, href: "/nechband/nechband (2).jpg", alt: 'OtherView' },
                { id: 4, href: "/nechband/blackNeckband/nechbandBlack (2).jpg", alt: 'FrontView' },
                { id: 5, href: "/nechband/blackNeckband/nechbandBlack (3).jpg", alt: 'FrontView' },
            ],
            color: { id: 10, name: 'Black', hex: 'bg-black', selected: true },
            sizes: [],
        },
        {
            id: 11,
            name: 'Kammee Sliver and Green Neckband',
            brand: "Kammee",
            tagline: 'Style meets sound.',
            price: generateInteger(10000),
            reviewCount: generateInteger(100000),
            averageRating: generateOneDecimalUnder5(),
            images: [
                { id: 1, href: "/nechband/greenNeckBand/nechbandSliverAndGreen (1).jpg", alt: 'FrontView' },
                { id: 2, href: "/nechband/nechband (1).jpg", alt: 'OtherView' },
                { id: 3, href: "/nechband/nechband (2).jpg", alt: 'OtherView' },
                { id: 4, href: "/nechband/greenNeckBand/nechbandSliverAndGreen (2).jpg", alt: 'FrontView' },
                { id: 5, href: "/nechband/greenNeckBand/nechbandSliverAndGreen (3).jpg", alt: 'FrontView' },
                { id: 6, href: "/nechband/greenNeckBand/nechbandSliverAndGreen (4).jpg", alt: 'FrontView' },
                { id: 7, href: "/nechband/greenNeckBand/nechbandSliverAndGreen (5).jpg", alt: 'FrontView' },
            ],
            color: { id: 11, name: 'Green', hex: 'bg-[#BFD456]', selected: false },
            sizes: [],
        },
        {
            id: 12,
            name: 'Kammee Red Neckband',
            brand: "Kammee",
            tagline: 'Style meets sound.',
            price: generateInteger(10000),
            reviewCount: generateInteger(100000),
            averageRating: generateOneDecimalUnder5(),
            images: [
                { id: 1, href: "/nechband/redNeckband/nechbandRed (1).jpg", alt: 'FrontView' },
                { id: 2, href: "/nechband/nechband (1).jpg", alt: 'OtherView' },
                { id: 3, href: "/nechband/nechband (2).jpg", alt: 'OtherView' },
                { id: 4, href: "/nechband/redNeckband/nechbandRed (2).jpg", alt: 'FrontView' },
                { id: 5, href: "/nechband/redNeckband/nechbandRed (3).jpg", alt: 'FrontView' },
            ],
            color: { id: 12, name: 'Red', hex: 'bg-[#FD1924]', selected: false },
            sizes: [],
        },
    ],
};

export const productsDuplicate = [
    {
        id: 1,
        groupId: 1000,
        name: 'Khapara Black Shoe',
        brand: "Khapara",
        tagline: 'Elegance in every step.',
        price: generateInteger(10000),
        reviewCount: generateInteger(10000),
        averageRating: generateOneDecimalUnder5(),
        images: [
            { id: 1, href: "/shoe/blackshoe/shoe (1).png", alt: 'AngledView' },
            { id: 2, href: "/shoe/blackshoe/shoe (2).png", alt: 'BackView' },
            { id: 3, href: "/shoe/blackshoe/shoe (3).png", alt: 'FrntView' },
            { id: 4, href: "/shoe/blackshoe/shoe (4).png", alt: 'LeftSideView' },
            { id: 5, href: "/shoe/blackshoe/shoe (5).png", alt: 'RightSideView' },
        ],
        color: { id: 1, name: 'Black', hex: 'bg-black', selected: true },
        sizes: [
            { label: '5 (24.1cm)', value: 's5', selected: true },
            { label: '6 (24.8cm)', value: 's6' },
            { label: '7 (25.7cm)', value: 's7' },
            { label: '8 (26.5cm)', value: 's8' },
            { label: '9 (27.3cm)', value: 's9' },
            { label: '10 (28.1cm)', value: 's10' },
        ],
    },
    {
        id: 2,
        groupId: 1000,
        name: 'Khapara Blue Shoe',
        brand: "Khapara",
        tagline: 'Confidence crafted in every shoe.',
        price: generateInteger(10000),
        reviewCount: generateInteger(100000),
        averageRating: generateOneDecimalUnder5(),
        images: [
            { id: 1, href: "/shoe/blueshoe/shoe (1).png", alt: 'AngledView' },
            { id: 2, href: "/shoe/blueshoe/shoe (2).png", alt: 'BackView' },
            { id: 3, href: "/shoe/blueshoe/shoe (3).png", alt: 'FrntView' },
            { id: 4, href: "/shoe/blueshoe/shoe (4).png", alt: 'LeftSideView' },
            { id: 5, href: "/shoe/blueshoe/shoe (5).png", alt: 'RightSideView' },
        ],
        color: { id: 2, name: 'Blue', hex: 'bg-[#1C518F]', selected: false },
        sizes: [
            { label: '5 (24.1cm)', value: 's5', selected: true },
            { label: '6 (24.8cm)', value: 's6' },
            { label: '7 (25.7cm)', value: 's7' },
            { label: '8 (26.5cm)', value: 's8' },
            { label: '9 (27.3cm)', value: 's9' },
            { label: '10 (28.1cm)', value: 's10' },
        ],
    },
    {
        id: 3,
        groupId: 1000,
        name: 'Khapara Classic Bold Brown Shoe',
        brand: "Khapara",
        tagline: 'Timeless style, modern stride.',
        price: generateInteger(10000),
        reviewCount: generateInteger(100000),
        averageRating: generateOneDecimalUnder5(),
        images: [
            { id: 1, href: "/shoe/classic-bold-brown/shoe (1).png", alt: 'AngledView' },
            { id: 2, href: "/shoe/classic-bold-brown/shoe (2).png", alt: 'BackView' },
            { id: 3, href: "/shoe/classic-bold-brown/shoe (3).png", alt: 'FrntView' },
            { id: 4, href: "/shoe/classic-bold-brown/shoe (4).png", alt: 'LeftSideView' },
            { id: 5, href: "/shoe/classic-bold-brown/shoe (5).png", alt: 'RightSideView' },
        ],
        color: { id: 3, name: 'Bold Brown', hex: 'bg-[#5B3F34]', selected: false },
        sizes: [
            { label: '5 (24.1cm)', value: 's5', selected: true },
            { label: '6 (24.8cm)', value: 's6' },
            { label: '7 (25.7cm)', value: 's7' },
            { label: '8 (26.5cm)', value: 's8' },
            { label: '9 (27.3cm)', value: 's9' },
            { label: '10 (28.1cm)', value: 's10' },
        ],
    },
    {
        id: 4,
        groupId: 1000,
        name: 'Khapara Classic Brown Shoe',
        brand: "Khapara",
        tagline: 'Walk bold, walk classic.',
        price: generateInteger(10000),
        reviewCount: generateInteger(100000),
        averageRating: generateOneDecimalUnder5(),
        images: [
            { id: 1, href: "/shoe/classic-brown/shoe (1).png", alt: 'AngledView' },
            { id: 2, href: "/shoe/classic-brown/shoe (2).png", alt: 'BackView' },
            { id: 3, href: "/shoe/classic-brown/shoe (3).png", alt: 'FrntView' },
            { id: 4, href: "/shoe/classic-brown/shoe (4).png", alt: 'LeftSideView' },
            { id: 5, href: "/shoe/classic-brown/shoe (5).png", alt: 'RightSideView' },
        ],
        color: { id: 4, name: 'Classic Brown', hex: 'bg-[#B07A68]', selected: false },
        sizes: [
            { label: '5 (24.1cm)', value: 's5', selected: true },
            { label: '6 (24.8cm)', value: 's6' },
            { label: '7 (25.7cm)', value: 's7' },
            { label: '8 (26.5cm)', value: 's8' },
            { label: '9 (27.3cm)', value: 's9' },
            { label: '10 (28.1cm)', value: 's10' },
        ],
    },
    {
        id: 5,
        groupId: 1000,
        name: 'Khapara White Shoe',
        brand: "Khapara",
        tagline: 'Sophistication from heel to toe.',
        price: generateInteger(10000),
        reviewCount: generateInteger(100000),
        averageRating: generateOneDecimalUnder5(),
        images: [
            { id: 1, href: "/shoe/whiteshoe/shoe (1).png", alt: 'AngledView' },
            { id: 2, href: "/shoe/whiteshoe/shoe (2).png", alt: 'BackView' },
            { id: 3, href: "/shoe/whiteshoe/shoe (3).png", alt: 'FrntView' },
            { id: 4, href: "/shoe/whiteshoe/shoe (4).png", alt: 'LeftSideView' },
            { id: 5, href: "/shoe/whiteshoe/shoe (5).png", alt: 'RightSideView' },
        ],
        color: { id: 5, name: 'White', hex: 'bg-white', selected: false },
        sizes: [
            { label: '5 (24.1cm)', value: 's5', selected: true },
            { label: '6 (24.8cm)', value: 's6' },
            { label: '7 (25.7cm)', value: 's7' },
            { label: '8 (26.5cm)', value: 's8' },
            { label: '9 (27.3cm)', value: 's9' },
            { label: '10 (28.1cm)', value: 's10' },
        ],
    },
    {
        id: 6,
        groupId: 1000,
        name: 'Khapara Red Shoe',
        brand: "Khapara",
        tagline: 'The power of the shoe, perfected.',
        price: generateInteger(10000),
        reviewCount: generateInteger(100000),
        averageRating: generateOneDecimalUnder5(),
        images: [
            { id: 1, href: "/shoe/redshoe/shoe (1).png", alt: 'AngledView' },
            { id: 2, href: "/shoe/redshoe/shoe (2).png", alt: 'BackView' },
            { id: 3, href: "/shoe/redshoe/shoe (3).png", alt: 'FrntView' },
            { id: 4, href: "/shoe/redshoe/shoe (4).png", alt: 'LeftSideView' },
            { id: 5, href: "/shoe/redshoe/shoe (5).png", alt: 'RightSideView' },
        ],
        color: { id: 6, name: 'Red', hex: 'bg-[#F05554]', selected: false },
        sizes: [
            { label: '5 (24.1cm)', value: 's5', selected: true },
            { label: '6 (24.8cm)', value: 's6' },
            { label: '7 (25.7cm)', value: 's7' },
            { label: '8 (26.5cm)', value: 's8' },
            { label: '9 (27.3cm)', value: 's9' },
            { label: '10 (28.1cm)', value: 's10' },
        ],
    },
    {
        id: 7,
        groupId: 2000,
        name: 'Premium Watch',
        brand: "Premium",
        tagline: 'Crafted for those who lead.',
        price: generateInteger(10000),
        reviewCount: generateInteger(100000),
        averageRating: generateOneDecimalUnder5(),
        images: [
            { id: 1, href: "/watch/watch (1).png", alt: 'AngledView' },
            { id: 2, href: "/watch/watch (2).png", alt: 'FrontView' },
            { id: 3, href: "/watch/watch (3).png", alt: 'RightSide' },
        ],
        color: { id: 7, name: 'Sliver', hex: 'bg-[#C0C0C0]', selected: false },
        sizes: [
            { label: 'Small (160mm)', value: 'small' },
            { label: 'Medium (180mm)', value: 'medium', selected: true },
            { label: 'Large (200mm)', value: 'large' },
        ],
    },
    {
        id: 8,
        groupId: 3000,
        name: 'Impex Battery Fan',
        brand: "Impex",
        tagline: 'Cool comfort, anywhere you go.',
        price: generateInteger(10000),
        reviewCount: generateInteger(100000),
        averageRating: generateOneDecimalUnder5(),
        images: [
            { id: 1, href: "/fan/batteryBlueFan/batteryFan (1).jpg", alt: 'FrontView' },
            { id: 2, href: "/fan/batteryBlueFan/batteryFan (2).jpg", alt: 'OtherView' },
            { id: 3, href: "/fan/batteryBlueFan/batteryFan (3).jpg", alt: 'OtherView' },
            { id: 4, href: "/fan/batteryBlueFan/batteryFan (4).jpg", alt: 'OtherView' },
            { id: 5, href: "/fan/batteryBlueFan/batteryFan (5).jpg", alt: 'OtherView' },
        ],
        color: { id: 8, name: 'Grey', hex: 'bg-[#8D8D8D]', selected: false },
        sizes: [],
    },
    {
        id: 9,
        groupId: 4000,
        name: 'Tanco Premium Ladies Purse',
        brand: "Tanco",
        tagline: 'Carry elegance, carry yourself.',
        price: generateInteger(10000),
        reviewCount: generateInteger(100000),
        averageRating: generateOneDecimalUnder5(),
        images: [
            { id: 1, href: "/ladiesPurse/ladiesPurse (1).jpg", alt: 'FrontView' },
            { id: 2, href: "/ladiesPurse/ladiesPurse (2).jpg", alt: 'OtherView' },
            { id: 3, href: "/ladiesPurse/ladiesPurse (3).jpg", alt: 'OtherView' },
            { id: 4, href: "/ladiesPurse/ladiesPurse (4).jpg", alt: 'OtherView' },
        ],
        color: { id: 9, name: 'Grey', hex: 'bg-[#F4EEF0]', selected: false },
        sizes: [],
    },
    {
        id: 10,
        groupId: 5000,
        name: 'Kammee Black Neckband',
        brand: "Kammee",
        tagline: 'Style meets sound.',
        price: generateInteger(10000),
        reviewCount: generateInteger(100000),
        averageRating: generateOneDecimalUnder5(),
        images: [
            { id: 1, href: "/nechband/blackNeckband/nechbandBlack (1).jpg", alt: 'FrontView' },
            { id: 2, href: "/nechband/nechband (1).jpg", alt: 'OtherView' },
            { id: 3, href: "/nechband/nechband (2).jpg", alt: 'OtherView' },
            { id: 4, href: "/nechband/blackNeckband/nechbandBlack (2).jpg", alt: 'FrontView' },
            { id: 5, href: "/nechband/blackNeckband/nechbandBlack (3).jpg", alt: 'FrontView' },
        ],
        color: { id: 10, name: 'Black', hex: 'bg-black', selected: true },
        sizes: [],
    },
    {
        id: 11,
        groupId: 5000,
        name: 'Kammee Sliver and Green Neckband',
        brand: "Kammee",
        tagline: 'Style meets sound.',
        price: generateInteger(10000),
        reviewCount: generateInteger(100000),
        averageRating: generateOneDecimalUnder5(),
        images: [
            { id: 1, href: "/nechband/greenNeckBand/nechbandSliverAndGreen (1).jpg", alt: 'FrontView' },
            { id: 2, href: "/nechband/nechband (1).jpg", alt: 'OtherView' },
            { id: 3, href: "/nechband/nechband (2).jpg", alt: 'OtherView' },
            { id: 4, href: "/nechband/greenNeckBand/nechbandSliverAndGreen (2).jpg", alt: 'FrontView' },
            { id: 5, href: "/nechband/greenNeckBand/nechbandSliverAndGreen (3).jpg", alt: 'FrontView' },
            { id: 6, href: "/nechband/greenNeckBand/nechbandSliverAndGreen (4).jpg", alt: 'FrontView' },
            { id: 7, href: "/nechband/greenNeckBand/nechbandSliverAndGreen (5).jpg", alt: 'FrontView' },
        ],
        color: { id: 11, name: 'Green', hex: 'bg-[#BFD456]', selected: false },
        sizes: [],
    },
    {
        id: 12,
        groupId: 5000,
        name: 'Kammee Red Neckband',
        brand: "Kammee",
        tagline: 'Style meets sound.',
        price: generateInteger(10000),
        reviewCount: generateInteger(100000),
        averageRating: generateOneDecimalUnder5(),
        images: [
            { id: 1, href: "/nechband/redNeckband/nechbandRed (1).jpg", alt: 'FrontView' },
            { id: 2, href: "/nechband/nechband (1).jpg", alt: 'OtherView' },
            { id: 3, href: "/nechband/nechband (2).jpg", alt: 'OtherView' },
            { id: 4, href: "/nechband/redNeckband/nechbandRed (2).jpg", alt: 'FrontView' },
            { id: 5, href: "/nechband/redNeckband/nechbandRed (3).jpg", alt: 'FrontView' },
        ],
        color: { id: 12, name: 'Red', hex: 'bg-[#FD1924]', selected: false },
        sizes: [],
    },
];