function generateInteger(int) {
    return Math.floor(Math.random() * int);
}

function generateOneDecimalUnder5() {
    let randomNumber = Math.random() * 5;
    return Math.round(randomNumber * 10) / 10;
}

export const products = [
    {
        id: 1,
        groupId: 1000,
        name: 'Khapara Black Shoe',
        brand: "Khapara",
        tagline: 'Elegance in every step.',
        price: generateInteger(1000),
        reviewCount: generateInteger(1000),
        averageRating: generateOneDecimalUnder5(),
        gender: ["Men", "Women", "Unisex"],
        images: [
            { id: 1, href: "/shoe/blackshoe/shoe (1).png", alt: 'AngledView' },
            { id: 2, href: "/shoe/blackshoe/shoe (2).png", alt: 'BackView' },
            { id: 3, href: "/shoe/blackshoe/shoe (3).png", alt: 'FrntView' },
            { id: 4, href: "/shoe/blackshoe/shoe (4).png", alt: 'LeftSideView' },
            { id: 5, href: "/shoe/blackshoe/shoe (5).png", alt: 'RightSideView' },
        ],
        color: { id: 1, name: 'Black', hex: 'bg-black', selected: true },
        sizes: [
            { label: '5 (24.1cm)', value: 's5', selected: true },
            { label: '6 (24.8cm)', value: 's6' },
            { label: '7 (25.7cm)', value: 's7' },
            { label: '8 (26.5cm)', value: 's8' },
            { label: '9 (27.3cm)', value: 's9' },
            { label: '10 (28.1cm)', value: 's10' },
        ],
        specifications: [
            { label: 'Style Name', value: 'Performance Road Runner 3.0' },
            { label: 'Toe Style', value: 'Round Toe' },
            { label: 'Sport Type', value: 'Running, Cross-Training, Walking' },
            { label: 'Shoe Type', value: 'Athletic Trainer (Neutral)' },
            { label: 'Upper Material', value: 'Breathable Mesh with Synthetic Overlays' },
            { label: 'Sole Material', value: 'Durable Rubber Outsole, EVA Foam Midsole' },
            { label: 'Closure Type', value: 'Lace-Up' },
            { label: 'Heel Type', value: 'Flat/Block' },
            { label: 'Water Resistance Level', value: 'None (Breathable Mesh)' },
            { label: 'Country of Origin', value: 'Vietnam' },
            { label: 'Item Weight', value: '800 g' },
            { label: 'Item Dimensions (LxWxH)', value: '24.1 x 10 x 8 centimeters' },
            {
                label: 'Key Features', value:
                    ['Moderate cushioning for shock absorption',
                        'Speckled midsole design',
                        'Multi-directional traction tread',
                        'Reinforced heel counter for stability']
            },
        ],
    },
    {
        id: 2,
        groupId: 1000,
        name: 'Khapara Blue Shoe',
        brand: "Khapara",
        tagline: 'Confidence crafted in every shoe.',
        price: generateInteger(1000),
        reviewCount: generateInteger(100000),
        averageRating: generateOneDecimalUnder5(),
        gender: ["Men", "Women", "Unisex"],
        images: [
            { id: 1, href: "/shoe/blueshoe/shoe (1).png", alt: 'AngledView' },
            { id: 2, href: "/shoe/blueshoe/shoe (2).png", alt: 'BackView' },
            { id: 3, href: "/shoe/blueshoe/shoe (3).png", alt: 'FrntView' },
            { id: 4, href: "/shoe/blueshoe/shoe (4).png", alt: 'LeftSideView' },
            { id: 5, href: "/shoe/blueshoe/shoe (5).png", alt: 'RightSideView' },
        ],
        color: { id: 2, name: 'Blue', hex: 'bg-[#1C518F]', selected: false },
        sizes: [
            { label: '5 (24.1cm)', value: 's5', selected: true },
            { label: '6 (24.8cm)', value: 's6' },
            { label: '7 (25.7cm)', value: 's7' },
            { label: '8 (26.5cm)', value: 's8' },
            { label: '9 (27.3cm)', value: 's9' },
            { label: '10 (28.1cm)', value: 's10' },
        ],
        specifications: [
            { "label": "Style Name", "value": "Velocity Sprint Runner X2" },
            { "label": "Toe Style", "value": "Round Toe" },
            { "label": "Sport Type", "value": "Running, Cross-Training, Walking" },
            { "label": "Shoe Type", "value": "Athletic Trainer (Neutral)" },
            { "label": "Upper Material", "value": "Breathable Mesh with Synthetic Overlays" },
            { "label": "Sole Material", "value": "Durable Rubber Outsole, EVA Foam Midsole" },
            { "label": "Closure Type", "value": "Lace-Up" },
            { "label": "Heel Type", "value": "Flat/Block" },
            { "label": "Water Resistance Level", "value": "None (Breathable Mesh)" },
            { "label": "Country of Origin", "value": "Vietnam" },
            { "label": "Item Weight", "value": "800 g" },
            { "label": "Item Dimensions (LxWxH)", "value": "24.1 x 10 x 8 centimeters" },
            {
                "label": "Key Features", "value": [
                    "Moderate cushioning for shock absorption",
                    "Speckled midsole design",
                    "Multi-directional traction tread",
                    "Reinforced heel counter for stability"
                ]
            }
        ],
    },
    {
        id: 3,
        groupId: 1000,
        name: 'Khapara Classic Bold Brown Shoe',
        brand: "Khapara",
        tagline: 'Timeless style, modern stride.',
        price: generateInteger(1000),
        reviewCount: generateInteger(100000),
        averageRating: generateOneDecimalUnder5(),
        gender: ["Men"],
        images: [
            { id: 1, href: "/shoe/classic-bold-brown/shoe (1).png", alt: 'AngledView' },
            { id: 2, href: "/shoe/classic-bold-brown/shoe (2).png", alt: 'BackView' },
            { id: 3, href: "/shoe/classic-bold-brown/shoe (3).png", alt: 'FrntView' },
            { id: 4, href: "/shoe/classic-bold-brown/shoe (4).png", alt: 'LeftSideView' },
            { id: 5, href: "/shoe/classic-bold-brown/shoe (5).png", alt: 'RightSideView' },
        ],
        color: { id: 3, name: 'Bold Brown', hex: 'bg-[#5B3F34]', selected: false },
        sizes: [
            { label: '5 (24.1cm)', value: 's5', selected: true },
            { label: '6 (24.8cm)', value: 's6' },
            { label: '7 (25.7cm)', value: 's7' },
            { label: '8 (26.5cm)', value: 's8' },
            { label: '9 (27.3cm)', value: 's9' },
            { label: '10 (28.1cm)', value: 's10' },
        ],
        specifications: [
            { "label": "Style Name", "value": "Classic Bold Brown" },
            { "label": "Toe Style", "value": "Round Toe" },
            { "label": "Sport Type", "value": "Walking, Casual" },
            { "label": "Shoe Type", "value": "Casual Sneaker" },
            { "label": "Upper Material", "value": "Premium Leather with Synthetic Overlays" },
            { "label": "Sole Material", "value": "Durable Rubber Outsole, EVA Foam Midsole" },
            { "label": "Closure Type", "value": "Lace-Up" },
            { "label": "Heel Type", "value": "Flat/Block" },
            {
                label: 'Key Features',
                value: [
                    'Premium leather upper for durability',
                    'EVA foam midsole for cushioning',
                    'Multi-directional traction tread',
                    'Reinforced heel counter for stability'
                ]
            }
        ]
    },
    {
        id: 4,
        groupId: 1000,
        name: 'Khapara Classic Brown Shoe',
        brand: "Khapara",
        tagline: 'Walk bold, walk classic.',
        price: generateInteger(1000),
        reviewCount: generateInteger(100000),
        averageRating: generateOneDecimalUnder5(),
        gender: ["Men"],
        images: [
            { id: 1, href: "/shoe/classic-brown/shoe (1).png", alt: 'AngledView' },
            { id: 2, href: "/shoe/classic-brown/shoe (2).png", alt: 'BackView' },
            { id: 3, href: "/shoe/classic-brown/shoe (3).png", alt: 'FrntView' },
            { id: 4, href: "/shoe/classic-brown/shoe (4).png", alt: 'LeftSideView' },
            { id: 5, href: "/shoe/classic-brown/shoe (5).png", alt: 'RightSideView' },
        ],
        color: { id: 4, name: 'Classic Brown', hex: 'bg-[#B07A68]', selected: false },
        sizes: [
            { label: '5 (24.1cm)', value: 's5', selected: true },
            { label: '6 (24.8cm)', value: 's6' },
            { label: '7 (25.7cm)', value: 's7' },
            { label: '8 (26.5cm)', value: 's8' },
            { label: '9 (27.3cm)', value: 's9' },
            { label: '10 (28.1cm)', value: 's10' },
        ],
        specifications: [
            { "label": "Style Name", "value": "Classic Bold Brown" },
            { "label": "Toe Style", "value": "Round Toe" },
            { "label": "Sport Type", "value": "Walking, Casual" },
            { "label": "Shoe Type", "value": "Casual Sneaker" },
            { "label": "Upper Material", "value": "Premium Leather with Synthetic Overlays" },
            { "label": "Sole Material", "value": "Durable Rubber Outsole, EVA Foam Midsole" },
            { "label": "Closure Type", "value": "Lace-Up" },
            { "label": "Heel Type", "value": "Flat/Block" },
            {
                label: 'Key Features',
                value: [
                    'Premium leather upper for durability',
                    'EVA foam midsole for cushioning',
                    'Multi-directional traction tread',
                    'Reinforced heel counter for stability'
                ]
            }
        ]
    },
    {
        id: 5,
        groupId: 1000,
        name: 'Khapara White Shoe',
        brand: "Khapara",
        tagline: 'Sophistication from heel to toe.',
        price: generateInteger(1000),
        reviewCount: generateInteger(100000),
        averageRating: generateOneDecimalUnder5(),
        gender: ["Men", "Women", "Unisex"],
        images: [
            { id: 1, href: "/shoe/whiteshoe/shoe (1).png", alt: 'AngledView' },
            { id: 2, href: "/shoe/whiteshoe/shoe (2).png", alt: 'BackView' },
            { id: 3, href: "/shoe/whiteshoe/shoe (3).png", alt: 'FrntView' },
            { id: 4, href: "/shoe/whiteshoe/shoe (4).png", alt: 'LeftSideView' },
            { id: 5, href: "/shoe/whiteshoe/shoe (5).png", alt: 'RightSideView' },
        ],
        color: { id: 5, name: 'White', hex: 'bg-white', selected: false },
        sizes: [
            { label: '5 (24.1cm)', value: 's5', selected: true },
            { label: '6 (24.8cm)', value: 's6' },
            { label: '7 (25.7cm)', value: 's7' },
            { label: '8 (26.5cm)', value: 's8' },
            { label: '9 (27.3cm)', value: 's9' },
            { label: '10 (28.1cm)', value: 's10' },
        ],
        specifications: [
            { "label": "Style Name", "value": "Performance Road Runner 3.0" },
            { "label": "Toe Style", "value": "Round Toe" },
            { "label": "Sport Type", "value": "Walking, Casual" },
            { "label": "Shoe Type", "value": "Casual Sneaker" },
            { "label": "Upper Material", "value": "Premium Leather with Synthetic Overlays" },
            { "label": "Sole Material", "value": "Durable Rubber Outsole, EVA Foam Midsole" },
            { "label": "Closure Type", "value": "Lace-Up" },
            { "label": "Heel Type", "value": "Flat/Block" },
            {
                label: 'Key Features',
                value: [
                    'Premium leather upper for durability',
                    'EVA foam midsole for cushioning',
                    'Multi-directional traction tread',
                    'Reinforced heel counter for stability'
                ]
            }
        ]
    },
    {
        id: 6,
        groupId: 1000,
        name: 'Khapara Red Shoe',
        brand: "Khapara",
        tagline: 'The power of the shoe, perfected.',
        price: generateInteger(1000),
        reviewCount: generateInteger(100000),
        averageRating: generateOneDecimalUnder5(),
        gender: ["Men", "Women", "Unisex"],
        images: [
            { id: 1, href: "/shoe/redshoe/shoe (1).png", alt: 'AngledView' },
            { id: 2, href: "/shoe/redshoe/shoe (2).png", alt: 'BackView' },
            { id: 3, href: "/shoe/redshoe/shoe (3).png", alt: 'FrntView' },
            { id: 4, href: "/shoe/redshoe/shoe (4).png", alt: 'LeftSideView' },
            { id: 5, href: "/shoe/redshoe/shoe (5).png", alt: 'RightSideView' },
        ],
        color: { id: 6, name: 'Red', hex: 'bg-[#F05554]', selected: false },
        sizes: [
            { label: '5 (24.1cm)', value: 's5', selected: true },
            { label: '6 (24.8cm)', value: 's6' },
            { label: '7 (25.7cm)', value: 's7' },
            { label: '8 (26.5cm)', value: 's8' },
            { label: '9 (27.3cm)', value: 's9' },
            { label: '10 (28.1cm)', value: 's10' },
        ],
        specifications: [
            { "label": "Style Name", "value": "Performance Road Runner 3.0" },
            { "label": "Toe Style", "value": "Round Toe" },
            { "label": "Sport Type", "value": "Walking, Casual" },
            { "label": "Shoe Type", "value": "Casual Sneaker" },
            { "label": "Upper Material", "value": "Premium Leather with Synthetic Overlays" },
            { "label": "Sole Material", "value": "Durable Rubber Outsole, EVA Foam Midsole" },
            { "label": "Closure Type", "value": "Lace-Up" },
            { "label": "Heel Type", "value": "Flat/Block" },
            {
                label: 'Key Features',
                value: [
                    'Premium leather upper for durability',
                    'EVA foam midsole for cushioning',
                    'Multi-directional traction tread',
                    'Reinforced heel counter for stability'
                ]
            }
        ]
    },
    {
        id: 7,
        groupId: 2000,
        name: 'Premium Watch',
        brand: "Premium",
        tagline: 'Crafted for those who lead.',
        price: generateInteger(1000),
        reviewCount: generateInteger(100000),
        averageRating: generateOneDecimalUnder5(),
        gender: ["Men"],
        images: [
            { id: 1, href: "/watch/watch (1).png", alt: 'AngledView' },
            { id: 2, href: "/watch/watch (2).png", alt: 'FrontView' },
            { id: 3, href: "/watch/watch (3).png", alt: 'RightSide' },
        ],
        color: { id: 7, name: 'Sliver', hex: 'bg-[#C0C0C0]', selected: false },
        sizes: [
            { label: 'Small (160mm)', value: 'small' },
            { label: 'Medium (180mm)', value: 'medium', selected: true },
            { label: 'Large (200mm)', value: 'large' },
        ],
        specifications: [
            { label: 'Display Type', value: 'Analog' },
            { label: 'Movement', value: 'Quartz' },
            { label: 'Case Material', value: 'Stainless Steel' },
            { label: 'Band Material', value: 'Leather Strap' },
            { label: 'Water Resistance', value: '50 meters' },
            { label: 'Features', value: 'Date Display, Luminous Hands' },
            { label: 'Warranty', value: '2 years limited warranty' },
            { label: 'Country of Origin', value: 'Japan' },
            { label: 'Item Weight', value: '150 g' },
            { label: 'Item Dimensions (LxWxH)', value: '4.2 x 4.2 x 1.2 centimeters' },
            {
                label: 'Key Features', value: [
                    'Elegant design suitable for formal occasions',
                    'Durable stainless steel case',
                    'Leather strap for comfort',
                    'Water-resistant design'
                ]
            }
        ],
    },
    {
        id: 8,
        groupId: 3000,
        name: 'Impex Battery Fan',
        brand: "Impex",
        tagline: 'Cool comfort, anywhere you go.',
        price: generateInteger(1000),
        reviewCount: generateInteger(100000),
        averageRating: generateOneDecimalUnder5(),
        gender: ["Men", "Women", "Unisex"],
        images: [
            { id: 1, href: "/fan/batteryBlueFan/batteryFan (1).jpg", alt: 'FrontView' },
            { id: 2, href: "/fan/batteryBlueFan/batteryFan (2).jpg", alt: 'OtherView' },
            { id: 3, href: "/fan/batteryBlueFan/batteryFan (3).jpg", alt: 'OtherView' },
            { id: 4, href: "/fan/batteryBlueFan/batteryFan (4).jpg", alt: 'OtherView' },
            { id: 5, href: "/fan/batteryBlueFan/batteryFan (5).jpg", alt: 'OtherView' },
        ],
        color: { id: 8, name: 'Grey', hex: 'bg-[#8D8D8D]', selected: false },
        sizes: [],
        specifications: [
            { label: 'Power Source', value: 'Battery Operated' },
            { label: 'Number of Speeds', value: '3' },
            { label: 'Battery Life', value: '10 hours' },
            { label: 'Charging Time', value: '2 hours' },
            { label: 'Warranty', value: '1 year limited warranty' },
            { label: 'Country of Origin', value: 'China' },
            { label: 'Item Weight', value: '250 g' },
            { label: 'Item Dimensions (LxWxH)', value: '15 x 10 x 5 centimeters' },
            {
                label: 'Key Features',
                value: [
                    '3-speed operation for customizable airflow',
                    'Long-lasting battery with quick charging',
                    'Compact and portable design',
                    'Quiet operation for comfortable use'
                ]
            }
        ],
    },
    {
        id: 9,
        groupId: 4000,
        name: 'Tanco Premium Ladies Purse',
        brand: "Tanco",
        tagline: 'Carry elegance, carry yourself.',
        price: generateInteger(1000),
        reviewCount: generateInteger(100000),
        averageRating: generateOneDecimalUnder5(),
        gender: ["Women"],
        images: [
            { id: 1, href: "/ladiesPurse/ladiesPurse (1).jpg", alt: 'FrontView' },
            { id: 2, href: "/ladiesPurse/ladiesPurse (2).jpg", alt: 'OtherView' },
            { id: 3, href: "/ladiesPurse/ladiesPurse (3).jpg", alt: 'OtherView' },
            { id: 4, href: "/ladiesPurse/ladiesPurse (4).jpg", alt: 'OtherView' },
        ],
        color: { id: 9, name: 'Grey', hex: 'bg-[#F4EEF0]', selected: false },
        sizes: [],
        specifications: [
            { label: 'Material', value: 'Genuine Leather' },
            { label: 'Dimensions', value: '25cm x 15cm x 10cm' },
            { label: 'Compartments', value: '3 main compartments, 2 side pockets' },
            { label: 'Closure Type', value: 'Zipper and Magnetic Snap' },
            { label: 'Strap Type', value: 'Adjustable Shoulder Strap' },
            { label: 'Warranty', value: '6 months limited warranty' },
            { label: 'Country of Origin', value: 'Italy' },
            { label: 'Item Weight', value: '500 g' },
            { label: 'Item Dimensions (LxWxH)', value: '25 x 15 x 10 centimeters' },
            {
                label: 'Key Features',
                value: [
                    'Premium genuine leather for durability',
                    'Spacious compartments for organization',
                    'Elegant design suitable for all occasions',
                    'Adjustable strap for comfortable carrying'
                ]
            }
        ],
    },
    {
        id: 10,
        groupId: 5000,
        name: 'Kammee Black Neckband',
        brand: "Kammee",
        tagline: 'Style meets sound.',
        price: generateInteger(1000),
        reviewCount: generateInteger(100000),
        averageRating: generateOneDecimalUnder5(),
        gender: ["Men", "Women", "Unisex"],
        images: [
            { id: 1, href: "/nechband/blackNeckband/nechbandBlack (1).jpg", alt: 'FrontView' },
            { id: 2, href: "/nechband/nechband (1).jpg", alt: 'OtherView' },
            { id: 3, href: "/nechband/nechband (2).jpg", alt: 'OtherView' },
            { id: 4, href: "/nechband/blackNeckband/nechbandBlack (2).jpg", alt: 'FrontView' },
            { id: 5, href: "/nechband/blackNeckband/nechbandBlack (3).jpg", alt: 'FrontView' },
        ],
        color: { id: 10, name: 'Black', hex: 'bg-black', selected: true },
        sizes: [],
        specifications: [
            { label: 'Bluetooth Version', value: '5.0' },
            { label: 'Battery Life', value: '8 hours' },
            { label: 'Charging Time', value: '2 hours' },
            { label: 'Water Resistance', value: 'IPX5' },
            { label: 'Warranty', value: '1 year limited warranty' },
            { label: 'Country of Origin', value: 'China' },
            { label: 'Item Weight', value: '50 g' },
            { label: 'Item Dimensions (LxWxH)', value: '15 x 10 x 5 centimeters' },
            {
                label: 'Key Features',
                value: [
                    'Wireless Bluetooth 5.0 for stable connection',
                    '8-hour battery life for extended use',
                    '2-hour charging time for quick power-up',
                    'Waterproof IPX5 rating for durability'
                ]
            }
        ],
    },
    {
        id: 11,
        groupId: 5000,
        name: 'Kammee Sliver and Green Neckband',
        brand: "Kammee",
        tagline: 'Style meets sound.',
        price: generateInteger(1000),
        reviewCount: generateInteger(100000),
        averageRating: generateOneDecimalUnder5(),
        gender: ["Men", "Women", "Unisex"],
        images: [
            { id: 1, href: "/nechband/greenNeckBand/nechbandSliverAndGreen (1).jpg", alt: 'FrontView' },
            { id: 2, href: "/nechband/nechband (1).jpg", alt: 'OtherView' },
            { id: 3, href: "/nechband/nechband (2).jpg", alt: 'OtherView' },
            { id: 4, href: "/nechband/greenNeckBand/nechbandSliverAndGreen (2).jpg", alt: 'FrontView' },
            { id: 5, href: "/nechband/greenNeckBand/nechbandSliverAndGreen (3).jpg", alt: 'FrontView' },
            { id: 6, href: "/nechband/greenNeckBand/nechbandSliverAndGreen (4).jpg", alt: 'FrontView' },
            { id: 7, href: "/nechband/greenNeckBand/nechbandSliverAndGreen (5).jpg", alt: 'FrontView' },
        ],
        color: { id: 11, name: 'Green', hex: 'bg-[#BFD456]', selected: false },
        sizes: [],
        specifications: [
            { label: 'Bluetooth Version', value: '5.0' },
            { label: 'Battery Life', value: '8 hours' },
            { label: 'Charging Time', value: '2 hours' },
            { label: 'Water Resistance', value: 'IPX5' },
            { label: 'Warranty', value: '1 year limited warranty' },
            { label: 'Country of Origin', value: 'China' },
            { label: 'Item Weight', value: '50 g' },
            { label: 'Item Dimensions (LxWxH)', value: '15 x 10 x 5 centimeters' },
            {
                label: 'Key Features',
                value: [
                    'Wireless Bluetooth 5.0 for stable connection',
                    '8-hour battery life for extended use',
                    '2-hour charging time for quick power-up',
                    'Waterproof IPX5 rating for durability'
                ]
            }
        ],
    },
    {
        id: 12,
        groupId: 5000,
        name: 'Kammee Red Neckband',
        brand: "Kammee",
        tagline: 'Style meets sound.',
        price: generateInteger(1000),
        reviewCount: generateInteger(100000),
        averageRating: generateOneDecimalUnder5(),
        gender: ["Men", "Women", "Unisex"],
        images: [
            { id: 1, href: "/nechband/redNeckband/nechbandRed (1).jpg", alt: 'FrontView' },
            { id: 2, href: "/nechband/nechband (1).jpg", alt: 'OtherView' },
            { id: 3, href: "/nechband/nechband (2).jpg", alt: 'OtherView' },
            { id: 4, href: "/nechband/redNeckband/nechbandRed (2).jpg", alt: 'FrontView' },
            { id: 5, href: "/nechband/redNeckband/nechbandRed (3).jpg", alt: 'FrontView' },
        ],
        color: { id: 12, name: 'Red', hex: 'bg-[#FD1924]', selected: false },
        sizes: [],
        specifications: [
            { label: 'Bluetooth Version', value: '5.0' },
            { label: 'Battery Life', value: '8 hours' },
            { label: 'Charging Time', value: '2 hours' },
            { label: 'Water Resistance', value: 'IPX5' },
            { label: 'Warranty', value: '1 year limited warranty' },
            { label: 'Country of Origin', value: 'China' },
            { label: 'Item Weight', value: '50 g' },
            { label: 'Item Dimensions (LxWxH)', value: '15 x 10 x 5 centimeters' },
            {
                label: 'Key Features',
                value: [
                    'Wireless Bluetooth 5.0 for stable connection',
                    '8-hour battery life for extended use',
                    '2-hour charging time for quick power-up',
                    'Waterproof IPX5 rating for durability'
                ]
            }
        ],
    },
];

export const myWishlist = [
    {
        wishlistId: "CUST1001-WL1",
        productId: 1,
        customerId: "CUST1001",
        name: "Khapara Black Shoe",
        price: 91,
        image: "/shoe/blackshoe/shoe (1).png",
        color: "Black",
        size: "s5"
    },
    {
        wishlistId: "CUST1001-WL2",
        productId: 8,
        customerId: "CUST1001",
        name: "Impex Battery Fan",
        price: 21,
        image: "/fan/batteryBlueFan/batteryFan (1).jpg",
        color: "Grey",
        size: ""
    }
];

export const cartList = [
    {
        cartlistId: 1,
        productId: 1,
        customerId: "CUST1001",
        quantity: 1,
        name: "Khapara Black Shoe",
        price: 6486,
        image: "/shoe/blackshoe/shoe (1).png",
        color: "Black",
        size: "s9",
    },
    {
        cartlistId: 2,
        productId: 12,
        customerId: "CUST1001",
        color: "Red",
        size: "",
        quantity: 2,
        name: "Kammee Red Neckband",
        price: 5142,
        image: "/nechband/blackNeckband/nechbandBlack (1).jpg",
    },
    {
        cartlistId: 3,
        productId: 7,
        customerId: "CUST1001",
        color: "Sliver",
        size: "medium",
        quantity: 4,
        name: 'Premium Watch',
        price: 150,
        image: "/watch/watch (1).png",
    },
    {
        cartlistId: 4,
        productId: 8,
        customerId: "CUST1001",
        color: "Grey",
        size: "",
        quantity: 1,
        name: 'Impex Battery Fan',
        price: 600,
        image: "/fan/batteryBlueFan/batteryFan (1).jpg",
    },
];

export const shippingInfo = [
    {
        id: 1,
        name: 'Alex Thompson',
        address: ['123 Maple Street, Apt 4B', 'Springfield, IL', '62704'],
        label: "home",
    },
    {
        id: 2,
        name: "Muniyamma",
        address: ["10, Mukkama street", "kekkuran, Tamil nadu", "617000"],
        nearByLandmark: "Mangama bus stop",
        emailId: "muniyamma@gmail.com",
        telephoneNumber: "9988776655",
        label: "apartment"
    }
];

export const promoCodes = [
    { code: "FIRST20", percentage: 0.20 },
    { code: "SECOND10", percentage: 0.10 },
    { code: "DIWALI15", percentage: 0.15 }
];

export const paymentInfo = [
    {
        id: 1,
        cardNumber: "1234123412341234",
        cardHolderName: "John Deo",
        cardExpirationDate: "01/20",
        cardCVVNumber: "123",
        paymentType: "Credit Card",
        isDefault: true
    },
    {
        id: 2,
        cardNumber: "1234123412340000",
        cardHolderName: "John Deo",
        cardExpirationDate: "02/16",
        cardCVVNumber: "456",
        paymentType: "Debit Card",
        isDefault: false
    },
];

export const totalSummarys = [
    {
        orderId: "3e5b7884-c8c2-4cef-a07e-6c3d55421a7d",
        congineeDetail: {
            id: 1,
            name: 'Alex Thompson',
            address: ['123 Maple Street, Apt 4B', 'Springfield, IL', '62704'],
            label: "home",
        },
        shippingMethod: {
            id: "express",
            name: "Overnight Express",
            price: 100,
            eta: "Thu Dec 06 2025 20:22:35 GMT+0530",
            isPopular: false
        },
        paymentMethod: {
            id: 1,
            paymentType: "COD"
        },
        trackItemsIds: [
            "3e5b7884-c8c2-4cef-a07e-6c3d55421a71",
            "3e5b7884-c8c2-4cef-a07e-6c3d55421a72",
            "3e5b7884-c8c2-4cef-a07e-6c3d55421a73",
            "3e5b7884-c8c2-4cef-a07e-6c3d55421a74",],
        totalSummary: {
            subtotal: 577,
            deliveryFee: 100,
            marketPlaceFee: 5,
            total: 682,
        },
        deliveryStatus: {
            orderDate: "Thu Dec 06 2025 20:22:35 GMT+0530",
            status: "Pending",
        },
    },
    {
        orderId: "3e5b7884-c8c2-4cef-a07e-6c3d55421a7e",
        congineeDetail: {
            id: 2,
            name: "Muniyamma",
            address: [
                "10, Mukkama street",
                "kekkuran, Tamil nadu",
                "617000"
            ],
            nearByLandmark: "Mangama bus stop",
            emailId: "muniyamma@gmail.com",
            telephoneNumber: "9988776655",
            label: "apartment"
        },
        shippingMethod: {
            id: "express",
            name: "Overnight Express",
            price: 100,
            eta: "Thu Dec 08 2025 20:22:35 GMT+0530",
            isPopular: false
        },
        paymentMethod: {
            id: 1,
            cardNumber: "1234123412341234",
            cardHolderName: "John Deo",
            cardExpirationDate: "04/12",
            cardCVVNumber: "123",
            paymentType: "Credit Card"
        },
        trackItemsIds: [
            "3e5b7884-c8c2-4cef-a07e-6c3d55421a75",
            "3e5b7884-c8c2-4cef-a07e-6c3d55421a76",
            "3e5b7884-c8c2-4cef-a07e-6c3d55421a77",
            "3e5b7884-c8c2-4cef-a07e-6c3d55421a78",],
        totalSummary: {
            subtotal: 1072,
            deliveryFee: 100,
            marketPlaceFee: 5,
            total: 1177
        },
        deliveryStatus: {
            orderDate: "Thu Dec 07 2025 20:22:35 GMT+0530",
            status: "Confirmed",
        },
    }
];

export const giftCardInfo = [
    {
        id: 1,
        customerId: "CUST1001",
        exchangeType: "SENDER",
        status: "CLAIMED",
        recipientName: "Jane Doe",
        recipientEmail: "jane.doe@example.com",
        senderName: "John Smith",
        message: "Happy Birthday to you..!",
        customAmount: 25.00,
        giftCardNum: "35b8f407-7356-408a-aee6-b101288f7261",
        purchaseDateTime: "Thu Jan 01 2025 20:22:35 GMT+0530"
    },
    {
        id: 2,
        customerId: "CUST1002",
        exchangeType: "RECIVED",
        status: "NOT-CLAIMED",
        recipientName: "Ambar Sharma",
        recipientEmail: "ambar.sharma@example.com",
        senderName: "Jothika Nair",
        message: "Happy Anniversary to you..!",
        customAmount: 250.00,
        giftCardNum: "35b8f407-7356-408a-aee6-b101288f7262",
        purchaseDateTime: "Thu Jan 02 2025 20:22:35 GMT+0530"
    },
    {
        id: 3,
        customerId: "CUST1003",
        exchangeType: "RECIVED",
        status: "CLAIMED",
        recipientName: "Robert Brown",
        recipientEmail: "robert.b@example.com",
        senderName: "Alice Green",
        message: "Thanks for your help!",
        customAmount: 50.00,
        giftCardNum: "4a2c1d9e-1f2e-4b3c-9d0a-5f6e7d8c9b1a",
        purchaseDateTime: "Thu Jan 03 2025 20:22:35 GMT+0530"
    },
    {
        id: 4,
        customerId: "CUST1004",
        exchangeType: "SENDER",
        status: "PENDING",
        recipientName: "Emily White",
        recipientEmail: "emily.w@example.com",
        senderName: "David Lee",
        message: "Just because!",
        customAmount: 10.00,
        giftCardNum: "7c5b3a1d-8e9f-4c0b-2a3d-6g7h8i9j0k1l",
        purchaseDateTime: "Thu Jan 04 2025 20:22:35 GMT+0530"
    },
    {
        id: 5,
        customerId: "CUST1005",
        exchangeType: "RECIVED",
        status: "CLAIMED",
        recipientName: "Michael Clark",
        recipientEmail: "michael.c@example.com",
        senderName: "Sarah Adams",
        message: "Enjoy!",
        customAmount: 100.00,
        giftCardNum: "1f3e5d7c-9b0a-2d4f-6e8h-0a1b2c3d4e5f",
        purchaseDateTime: "Thu Jan 05 2025 20:22:35 GMT+0530"
    },
    {
        id: 6,
        customerId: "CUST1006",
        exchangeType: "SENDER",
        status: "CANCELED",
        recipientName: "Olivia Wilson",
        recipientEmail: "olivia.w@example.com",
        senderName: "Chris Martin",
        message: "Sorry, this was a mistake.",
        customAmount: 75.00,
        giftCardNum: "8h7g6f5e-4d3c-2b1a-0a9b-8c7d6e5f4g3h",
        purchaseDateTime: "Thu Jan 06 2025 20:22:35 GMT+0530"
    },
    {
        id: 7,
        customerId: "CUST1007",
        exchangeType: "RECIVED",
        status: "NOT-CLAIMED",
        recipientName: "James Taylor",
        recipientEmail: "james.t@example.com",
        senderName: "Priya Singh",
        message: "Merry Christmas!",
        customAmount: 300.00,
        giftCardNum: "2c4d6f8a-0b1c-3d5e-7f9g-1h2i3j4k5l6m",
        purchaseDateTime: "Thu Jan 07 2025 20:22:35 GMT+0530"
    },
    {
        id: 8,
        customerId: "CUST1008",
        exchangeType: "SENDER",
        status: "CLAIMED",
        recipientName: "Sophia Miller",
        recipientEmail: "sophia.m@example.com",
        senderName: "Ben Davis",
        message: "Congratulations on your new job!",
        customAmount: 40.00,
        giftCardNum: "9g8f7e6d-5c4b-3a2b-1c0d-9e8f7g6h5i4j",
        purchaseDateTime: "Thu Jan 08 2025 20:22:35 GMT+0530"
    },
    {
        id: 9,
        customerId: "CUST1009",
        exchangeType: "RECIVED",
        status: "CLAIMED",
        recipientName: "William Harris",
        recipientEmail: "william.h@example.com",
        senderName: "Ava Jones",
        message: "Graduation gift!",
        customAmount: 500.00,
        giftCardNum: "3e2d1c0b-9a8f-7e6d-5c4b-3a2b1c0d9e8f",
        purchaseDateTime: "Thu Jan 09 2025 20:22:35 GMT+0530"
    },
    {
        id: 10,
        customerId: "CUST1010",
        exchangeType: "SENDER",
        status: "PENDING",
        recipientName: "Mia Garcia",
        recipientEmail: "mia.g@example.com",
        senderName: "Ethan Rodriguez",
        message: "Thinking of you.",
        customAmount: 20.00,
        giftCardNum: "6a5b4c3d-2e1f-0g9h-8i7j-6k5l4m3n2o1p",
        purchaseDateTime: "Thu Jan 10 2025 20:22:35 GMT+0530"
    },
    {
        id: 11,
        customerId: "CUST1011",
        exchangeType: "RECIVED",
        status: "NOT-CLAIMED",
        recipientName: "Noah Martinez",
        recipientEmail: "noah.m@example.com",
        senderName: "Chloe Hernandez",
        message: "Happy Easter!",
        customAmount: 15.00,
        giftCardNum: "0h1i2j3k-4l5m-6n7o-8p9q-0r1s2t3u4v5w",
        purchaseDateTime: "Thu Jan 11 2025 20:22:35 GMT+0530"
    },
    {
        id: 12,
        customerId: "CUST1012",
        exchangeType: "SENDER",
        status: "CLAIMED",
        recipientName: "Isabella Lopez",
        recipientEmail: "isabella.l@example.com",
        senderName: "Liam Perez",
        message: "A little something extra.",
        customAmount: 60.00,
        giftCardNum: "4d3c2b1a-0e9f-8g7h-6i5j-4k3l2m1n0o9p",
        purchaseDateTime: "Thu Jan 12 2025 20:22:35 GMT+0530"
    },
    {
        id: 13,
        customerId: "CUST1013",
        exchangeType: "RECIVED",
        status: "CLAIMED",
        recipientName: "Jacob Kim",
        recipientEmail: "jacob.k@example.com",
        senderName: "Emma Chen",
        message: "For your dedication!",
        customAmount: 80.00,
        giftCardNum: "7f6e5d4c-3b2a-1c0b-9d8e-7f6g5h4i3j2k",
        purchaseDateTime: "Thu Jan 13 2025 20:22:35 GMT+0530"
    },
    {
        id: 14,
        customerId: "CUST1014",
        exchangeType: "SENDER",
        status: "CANCELED",
        recipientName: "Ava Scott",
        recipientEmail: "ava.s@example.com",
        senderName: "Lucas Baker",
        message: "Duplicate order.",
        customAmount: 35.00,
        giftCardNum: "1a2b3c4d-5e6f-7g8h-9i0j-1k2l3m4n5o6p",
        purchaseDateTime: "Thu Jan 14 2025 20:22:35 GMT+0530"
    },
    {
        id: 15,
        customerId: "CUST1015",
        exchangeType: "RECIVED",
        status: "NOT-CLAIMED",
        recipientName: "Mason King",
        recipientEmail: "mason.k@example.com",
        senderName: "Charlotte Carter",
        message: "Welcome to the team!",
        customAmount: 120.00,
        giftCardNum: "5e4d3c2b-1a0e-9f8g-7h6i-5j4k3l2m1n0o",
        purchaseDateTime: "Thu Jan 15 2025 20:22:35 GMT+0530"
    },
    {
        id: 16,
        customerId: "CUST1016",
        exchangeType: "SENDER",
        status: "PENDING",
        recipientName: "Harper Hall",
        recipientEmail: "harper.h@example.com",
        senderName: "Elijah Evans",
        message: "Get well soon.",
        customAmount: 45.00,
        giftCardNum: "8c7d6e5f-4g3h-2i1j-0k9l-8m7n6o5p4q3r",
        purchaseDateTime: "Thu Jan 16 2025 20:22:35 GMT+0530"
    },
    {
        id: 17,
        customerId: "CUST1017",
        exchangeType: "RECIVED",
        status: "CLAIMED",
        recipientName: "Evelyn Ross",
        recipientEmail: "evelyn.r@example.com",
        senderName: "Alexander Fisher",
        message: "Just because I love you!",
        customAmount: 70.00,
        giftCardNum: "2g1f0e9d-8c7b-6a5b-4c3d-2e1f0g9h8i7j",
        purchaseDateTime: "Thu Jan 17 2025 20:22:35 GMT+0530"
    },
    {
        id: 18,
        customerId: "CUST1018",
        exchangeType: "SENDER",
        status: "CLAIMED",
        recipientName: "Logan Cook",
        recipientEmail: "logan.c@example.com",
        senderName: "Amelia Hayes",
        message: "Happy holidays!",
        customAmount: 90.00,
        giftCardNum: "6k5l4m3n-2o1p-0q9r-8s7t-6u5v4w3x2y1z",
        purchaseDateTime: "Thu Jan 18 2025 20:22:35 GMT+0530"
    },
    {
        id: 19,
        customerId: "CUST1019",
        exchangeType: "RECIVED",
        status: "NOT-CLAIMED",
        recipientName: "Ella Baker",
        recipientEmail: "ella.b@example.com",
        senderName: "Daniel Foster",
        message: "Welcome baby!",
        customAmount: 150.00,
        giftCardNum: "9b8a7c6d-5e4f-3g2h-1i0j-9k8l7m6n5o4p",
        purchaseDateTime: "Thu Jan 19 2025 20:22:35 GMT+0530"
    },
    {
        id: 20,
        customerId: "CUST1020",
        exchangeType: "SENDER",
        status: "PENDING",
        recipientName: "Henry Gray",
        recipientEmail: "henry.g@example.com",
        senderName: "Grace Jenkins",
        message: "Happy New Year!",
        customAmount: 5.00,
        giftCardNum: "3a4b5c6d-7e8f-9g0h-1i2j-3k4l5m6n7o8p",
        purchaseDateTime: "Thu Jan 20 2025 20:22:35 GMT+0530"
    }
];

export const itemsStatus = [
    {
        id: "3e5b7884-c8c2-4cef-a07e-6c3d55421a7d",
        items: [
            {
                id: 1,
                productId: 1,
                color: "Black",
                size: "s9",
                quantity: 1,
                name: "Khapara Black Shoe",
                price: 70,
                image: "/shoe/blackshoe/shoe (1).png",
                status: "Pending",
                orderDate: "Thu Dec 06 2025 20:22:35 GMT+0530",
                eta: "Thu Dec 06 2025 20:22:35 GMT+0530",
                ata: "Thu Jan 06 2025 20:22:35 GMT+0530",
            },
            {
                id: 2,
                productId: 12,
                color: "Red",
                size: "",
                quantity: 2,
                name: "Kammee Red Neckband",
                price: 62,
                image: "/nechband/blackNeckband/nechbandBlack (1).jpg",
                status: "Confirmed",
                orderDate: "Thu Dec 06 2025 20:22:35 GMT+0530",
                eta: "Thu Dec 06 2025 20:22:35 GMT+0530",
                ata: "Thu Jan 06 2025 20:22:35 GMT+0530",
            },
            {
                id: 3,
                productId: 7,
                color: "Sliver",
                size: "medium",
                quantity: 4,
                name: "Premium Watch",
                price: 14,
                image: "/watch/watch (1).png",
                status: "Shipped",
                orderDate: "Thu Dec 06 2025 20:22:35 GMT+0530",
                eta: "Thu Dec 06 2025 20:22:35 GMT+0530",
                ata: "Thu Jan 06 2025 20:22:35 GMT+0530",
            },
            {
                id: 4,
                productId: 8,
                color: "Grey",
                size: "",
                quantity: 1,
                name: "Impex Battery Fan",
                price: 53,
                image: "/fan/batteryBlueFan/batteryFan (1).jpg",
                status: "In Transit",
                orderDate: "Thu Dec 06 2025 20:22:35 GMT+0530",
                eta: "Thu Dec 06 2025 20:22:35 GMT+0530",
                ata: "Thu Jan 06 2025 20:22:35 GMT+0530",
            },
            {
                id: 5,
                productId: 1,
                color: "Black",
                size: "s9",
                quantity: 1,
                name: "Khapara Black Shoe",
                price: 11,
                image: "/shoe/blackshoe/shoe (1).png",
                status: "Out for Delivery",
                orderDate: "Thu Dec 06 2025 20:22:35 GMT+0530",
                eta: "Thu Dec 06 2025 20:22:35 GMT+0530",
                ata: "Thu Jan 06 2025 20:22:35 GMT+0530",
            },
            {
                id: 6,
                productId: 12,
                color: "Red",
                size: "",
                quantity: 2,
                name: "Kammee Red Neckband",
                price: 35,
                image: "/nechband/blackNeckband/nechbandBlack (1).jpg",
                status: "Delivered",
                orderDate: "Thu Dec 06 2025 20:22:35 GMT+0530",
                eta: "Thu Dec 06 2025 20:22:35 GMT+0530",
                ata: "Thu Jan 06 2025 20:22:35 GMT+0530",
            },
            {
                id: 7,
                productId: 7,
                color: "Sliver",
                size: "medium",
                quantity: 4,
                name: "Premium Watch",
                price: 28,
                image: "/watch/watch (1).png",
                status: "Pending",
                orderDate: "Thu Dec 06 2025 20:22:35 GMT+0530",
                eta: "Thu Dec 06 2025 20:22:35 GMT+0530",
                ata: "Thu Jan 06 2025 20:22:35 GMT+0530",
            },
            {
                id: 8,
                productId: 8,
                color: "Grey",
                size: "",
                quantity: 1,
                name: "Impex Battery Fan",
                price: 81,
                image: "/fan/batteryBlueFan/batteryFan (1).jpg",
                status: "Pending",
                orderDate: "Thu Dec 06 2025 20:22:35 GMT+0530",
                eta: "Thu Dec 06 2025 20:22:35 GMT+0530",
                ata: "Thu Jan 06 2025 20:22:35 GMT+0530",
            }],
    },
    {
        id: "855ddcf2-e2ea-4d84-9a79-625f787e5b27",
        items: [
            {
                id: 1,
                productId: 1,
                quantity: 1,
                name: "Khapara Black Shoe",
                price: 77,
                image: "/shoe/blackshoe/shoe (1).png",
                color: "Black",
                size: "s9",
                status: "Pending",
                orderDate: "Thu Dec 07 2025 20:22:35 GMT+0530",
                eta: "Thu Dec 08 2025 20:22:35 GMT+0530",
                ata: "Thu Jan 06 2025 20:22:35 GMT+0530"
            },
            {
                id: 2,
                productId: 12,
                color: "Red",
                size: "",
                quantity: 2,
                name: "Kammee Red Neckband",
                price: 16,
                image: "/nechband/blackNeckband/nechbandBlack (1).jpg",
                status: "Pending",
                orderDate: "Thu Dec 07 2025 20:22:35 GMT+0530",
                eta: "Thu Dec 08 2025 20:22:35 GMT+0530",
                ata: "Thu Jan 06 2025 20:22:35 GMT+0530"
            },
            {
                id: 3,
                productId: 7,
                color: "Sliver",
                size: "medium",
                quantity: 4,
                name: "Premium Watch",
                price: 10,
                image: "/watch/watch (1).png",
                status: "Pending",
                orderDate: "Thu Dec 07 2025 20:22:35 GMT+0530",
                eta: "Thu Dec 08 2025 20:22:35 GMT+0530",
                ata: "Thu Jan 06 2025 20:22:35 GMT+0530"
            },
            {
                id: 4,
                productId: 8,
                color: "Grey",
                size: "",
                quantity: 1,
                name: "Impex Battery Fan",
                price: 4,
                image: "/fan/batteryBlueFan/batteryFan (1).jpg",
                status: "Pending",
                orderDate: "Thu Dec 07 2025 20:22:35 GMT+0530",
                eta: "Thu Dec 08 2025 20:22:35 GMT+0530",
                ata: "Thu Jan 06 2025 20:22:35 GMT+0530"
            },
            {
                id: 5,
                productId: 1,
                color: "Black",
                size: "s9",
                quantity: 1,
                name: "Khapara Black Shoe",
                price: 57,
                image: "/shoe/blackshoe/shoe (1).png",
                status: "Pending",
                orderDate: "Thu Dec 07 2025 20:22:35 GMT+0530",
                eta: "Thu Dec 08 2025 20:22:35 GMT+0530",
                ata: "Thu Jan 06 2025 20:22:35 GMT+0530"
            },
            {
                id: 6,
                productId: 12,
                color: "Red",
                size: "",
                quantity: 2,
                name: "Kammee Red Neckband",
                price: 81,
                image: "/nechband/blackNeckband/nechbandBlack (1).jpg",
                status: "Pending",
                orderDate: "Thu Dec 07 2025 20:22:35 GMT+0530",
                eta: "Thu Dec 08 2025 20:22:35 GMT+0530",
                ata: "Thu Jan 06 2025 20:22:35 GMT+0530"
            },
            {
                id: 7,
                productId: 7,
                color: "Sliver",
                size: "medium",
                quantity: 4,
                name: "Premium Watch",
                price: 55,
                image: "/watch/watch (1).png",
                status: "Pending",
                orderDate: "Thu Dec 07 2025 20:22:35 GMT+0530",
                eta: "Thu Dec 08 2025 20:22:35 GMT+0530",
                ata: "Thu Jan 06 2025 20:22:35 GMT+0530"
            },
            {
                id: 8,
                productId: 8,
                color: "Grey",
                size: "",
                quantity: 1,
                name: "Impex Battery Fan",
                price: 71,
                image: "/fan/batteryBlueFan/batteryFan (1).jpg",
                status: "Pending",
                orderDate: "Thu Dec 07 2025 20:22:35 GMT+0530",
                eta: "Thu Dec 08 2025 20:22:35 GMT+0530",
                ata: "Thu Jan 06 2025 20:22:35 GMT+0530"
            }
        ],
    },
];

export const trackItems = [
    {
        trackId: "3e5b7884-c8c2-4cef-a07e-6c3d55421a71",
        productId: 1,
        color: "Black",
        size: "s9",
        quantity: 1,
        name: "Khapara Black Shoe",
        price: 70,
        image: "/shoe/blackshoe/shoe (1).png",
        status: "Pending",
        orderId: "3e5b7884-c8c2-4cef-a07e-6c3d55421a7d",
        orderDate: "Thu Dec 06 2025 20:22:35 GMT+0530",
        eta: "Thu Dec 06 2025 20:22:35 GMT+0530",
        ata: "Thu Jan 06 2025 20:22:35 GMT+0530",
    },
    {
        trackId: "3e5b7884-c8c2-4cef-a07e-6c3d55421a72",
        productId: 12,
        color: "Red",
        size: "",
        quantity: 2,
        name: "Kammee Red Neckband",
        price: 62,
        image: "/nechband/blackNeckband/nechbandBlack (1).jpg",
        status: "Confirmed",
        orderId: "3e5b7884-c8c2-4cef-a07e-6c3d55421a7d",
        orderDate: "Thu Dec 06 2025 20:22:35 GMT+0530",
        eta: "Thu Dec 06 2025 20:22:35 GMT+0530",
        ata: "Thu Jan 06 2025 20:22:35 GMT+0530",
    },
    {
        trackId: "3e5b7884-c8c2-4cef-a07e-6c3d55421a73",
        productId: 7,
        color: "Sliver",
        size: "medium",
        quantity: 4,
        name: "Premium Watch",
        price: 14,
        image: "/watch/watch (1).png",
        status: "Shipped",
        orderId: "3e5b7884-c8c2-4cef-a07e-6c3d55421a7d",
        orderDate: "Thu Dec 06 2025 20:22:35 GMT+0530",
        eta: "Thu Dec 06 2025 20:22:35 GMT+0530",
        ata: "Thu Jan 06 2025 20:22:35 GMT+0530",
    },
    {
        trackId: "3e5b7884-c8c2-4cef-a07e-6c3d55421a74",
        productId: 8,
        color: "Grey",
        size: "",
        quantity: 1,
        name: "Impex Battery Fan",
        price: 53,
        image: "/fan/batteryBlueFan/batteryFan (1).jpg",
        status: "In Transit",
        orderId: "3e5b7884-c8c2-4cef-a07e-6c3d55421a7d",
        orderDate: "Thu Dec 06 2025 20:22:35 GMT+0530",
        eta: "Thu Dec 06 2025 20:22:35 GMT+0530",
        ata: "Thu Jan 06 2025 20:22:35 GMT+0530",
    },
    {
        trackId: "3e5b7884-c8c2-4cef-a07e-6c3d55421a75",
        productId: 1,
        color: "Black",
        size: "s9",
        quantity: 1,
        name: "Khapara Black Shoe",
        price: 11,
        image: "/shoe/blackshoe/shoe (1).png",
        status: "Out for Delivery",
        orderId: "3e5b7884-c8c2-4cef-a07e-6c3d55421a7e",
        orderDate: "Thu Dec 06 2025 20:22:35 GMT+0530",
        eta: "Thu Dec 06 2025 20:22:35 GMT+0530",
        ata: "Thu Jan 06 2025 20:22:35 GMT+0530",
    },
    {
        trackId: "3e5b7884-c8c2-4cef-a07e-6c3d55421a76",
        productId: 12,
        color: "Red",
        size: "",
        quantity: 2,
        name: "Kammee Red Neckband",
        price: 35,
        image: "/nechband/blackNeckband/nechbandBlack (1).jpg",
        status: "Delivered",
        orderId: "3e5b7884-c8c2-4cef-a07e-6c3d55421a7e",
        orderDate: "Thu Dec 06 2025 20:22:35 GMT+0530",
        eta: "Thu Dec 06 2025 20:22:35 GMT+0530",
        ata: "Thu Jan 06 2025 20:22:35 GMT+0530",
    },
    {
        trackId: "3e5b7884-c8c2-4cef-a07e-6c3d55421a77",
        productId: 7,
        color: "Sliver",
        size: "medium",
        quantity: 4,
        name: "Premium Watch",
        price: 28,
        image: "/watch/watch (1).png",
        status: "Pending",
        orderId: "3e5b7884-c8c2-4cef-a07e-6c3d55421a7e",
        orderDate: "Thu Dec 06 2025 20:22:35 GMT+0530",
        eta: "Thu Dec 06 2025 20:22:35 GMT+0530",
        ata: "Thu Jan 06 2025 20:22:35 GMT+0530",
    },
    {
        trackId: "3e5b7884-c8c2-4cef-a07e-6c3d55421a78",
        productId: 8,
        color: "Grey",
        size: "",
        quantity: 1,
        name: "Impex Battery Fan",
        price: 81,
        image: "/fan/batteryBlueFan/batteryFan (1).jpg",
        status: "Pending",
        orderId: "3e5b7884-c8c2-4cef-a07e-6c3d55421a7e",
        orderDate: "Thu Dec 06 2025 20:22:35 GMT+0530",
        eta: "Thu Dec 06 2025 20:22:35 GMT+0530",
        ata: "Thu Jan 06 2025 20:22:35 GMT+0530",
    }
];
