function generateInteger(int) {
    return Math.floor(Math.random() * int);
}

function generateOneDecimalUnder5() {
    let randomNumber = Math.random() * 5;
    return Math.round(randomNumber * 10) / 10;
}

export const products = [
    {
        id: 1,
        groupId: 1000,
        name: 'Khapara Black Shoe',
        brand: "Khapara",
        tagline: 'Elegance in every step.',
        price: generateInteger(100),
        reviewCount: generateInteger(1000),
        averageRating: generateOneDecimalUnder5(),
        images: [
            { id: 1, href: "/shoe/blackshoe/shoe (1).png", alt: 'AngledView' },
            { id: 2, href: "/shoe/blackshoe/shoe (2).png", alt: 'BackView' },
            { id: 3, href: "/shoe/blackshoe/shoe (3).png", alt: 'FrntView' },
            { id: 4, href: "/shoe/blackshoe/shoe (4).png", alt: 'LeftSideView' },
            { id: 5, href: "/shoe/blackshoe/shoe (5).png", alt: 'RightSideView' },
        ],
        color: { id: 1, name: 'Black', hex: 'bg-black', selected: true },
        sizes: [
            { label: '5 (24.1cm)', value: 's5', selected: true },
            { label: '6 (24.8cm)', value: 's6' },
            { label: '7 (25.7cm)', value: 's7' },
            { label: '8 (26.5cm)', value: 's8' },
            { label: '9 (27.3cm)', value: 's9' },
            { label: '10 (28.1cm)', value: 's10' },
        ],
    },
    {
        id: 2,
        groupId: 1000,
        name: 'Khapara Blue Shoe',
        brand: "Khapara",
        tagline: 'Confidence crafted in every shoe.',
        price: generateInteger(100),
        reviewCount: generateInteger(100000),
        averageRating: generateOneDecimalUnder5(),
        images: [
            { id: 1, href: "/shoe/blueshoe/shoe (1).png", alt: 'AngledView' },
            { id: 2, href: "/shoe/blueshoe/shoe (2).png", alt: 'BackView' },
            { id: 3, href: "/shoe/blueshoe/shoe (3).png", alt: 'FrntView' },
            { id: 4, href: "/shoe/blueshoe/shoe (4).png", alt: 'LeftSideView' },
            { id: 5, href: "/shoe/blueshoe/shoe (5).png", alt: 'RightSideView' },
        ],
        color: { id: 2, name: 'Blue', hex: 'bg-[#1C518F]', selected: false },
        sizes: [
            { label: '5 (24.1cm)', value: 's5', selected: true },
            { label: '6 (24.8cm)', value: 's6' },
            { label: '7 (25.7cm)', value: 's7' },
            { label: '8 (26.5cm)', value: 's8' },
            { label: '9 (27.3cm)', value: 's9' },
            { label: '10 (28.1cm)', value: 's10' },
        ],
    },
    {
        id: 3,
        groupId: 1000,
        name: 'Khapara Classic Bold Brown Shoe',
        brand: "Khapara",
        tagline: 'Timeless style, modern stride.',
        price: generateInteger(100),
        reviewCount: generateInteger(100000),
        averageRating: generateOneDecimalUnder5(),
        images: [
            { id: 1, href: "/shoe/classic-bold-brown/shoe (1).png", alt: 'AngledView' },
            { id: 2, href: "/shoe/classic-bold-brown/shoe (2).png", alt: 'BackView' },
            { id: 3, href: "/shoe/classic-bold-brown/shoe (3).png", alt: 'FrntView' },
            { id: 4, href: "/shoe/classic-bold-brown/shoe (4).png", alt: 'LeftSideView' },
            { id: 5, href: "/shoe/classic-bold-brown/shoe (5).png", alt: 'RightSideView' },
        ],
        color: { id: 3, name: 'Bold Brown', hex: 'bg-[#5B3F34]', selected: false },
        sizes: [
            { label: '5 (24.1cm)', value: 's5', selected: true },
            { label: '6 (24.8cm)', value: 's6' },
            { label: '7 (25.7cm)', value: 's7' },
            { label: '8 (26.5cm)', value: 's8' },
            { label: '9 (27.3cm)', value: 's9' },
            { label: '10 (28.1cm)', value: 's10' },
        ],
    },
    {
        id: 4,
        groupId: 1000,
        name: 'Khapara Classic Brown Shoe',
        brand: "Khapara",
        tagline: 'Walk bold, walk classic.',
        price: generateInteger(100),
        reviewCount: generateInteger(100000),
        averageRating: generateOneDecimalUnder5(),
        images: [
            { id: 1, href: "/shoe/classic-brown/shoe (1).png", alt: 'AngledView' },
            { id: 2, href: "/shoe/classic-brown/shoe (2).png", alt: 'BackView' },
            { id: 3, href: "/shoe/classic-brown/shoe (3).png", alt: 'FrntView' },
            { id: 4, href: "/shoe/classic-brown/shoe (4).png", alt: 'LeftSideView' },
            { id: 5, href: "/shoe/classic-brown/shoe (5).png", alt: 'RightSideView' },
        ],
        color: { id: 4, name: 'Classic Brown', hex: 'bg-[#B07A68]', selected: false },
        sizes: [
            { label: '5 (24.1cm)', value: 's5', selected: true },
            { label: '6 (24.8cm)', value: 's6' },
            { label: '7 (25.7cm)', value: 's7' },
            { label: '8 (26.5cm)', value: 's8' },
            { label: '9 (27.3cm)', value: 's9' },
            { label: '10 (28.1cm)', value: 's10' },
        ],
    },
    {
        id: 5,
        groupId: 1000,
        name: 'Khapara White Shoe',
        brand: "Khapara",
        tagline: 'Sophistication from heel to toe.',
        price: generateInteger(100),
        reviewCount: generateInteger(100000),
        averageRating: generateOneDecimalUnder5(),
        images: [
            { id: 1, href: "/shoe/whiteshoe/shoe (1).png", alt: 'AngledView' },
            { id: 2, href: "/shoe/whiteshoe/shoe (2).png", alt: 'BackView' },
            { id: 3, href: "/shoe/whiteshoe/shoe (3).png", alt: 'FrntView' },
            { id: 4, href: "/shoe/whiteshoe/shoe (4).png", alt: 'LeftSideView' },
            { id: 5, href: "/shoe/whiteshoe/shoe (5).png", alt: 'RightSideView' },
        ],
        color: { id: 5, name: 'White', hex: 'bg-white', selected: false },
        sizes: [
            { label: '5 (24.1cm)', value: 's5', selected: true },
            { label: '6 (24.8cm)', value: 's6' },
            { label: '7 (25.7cm)', value: 's7' },
            { label: '8 (26.5cm)', value: 's8' },
            { label: '9 (27.3cm)', value: 's9' },
            { label: '10 (28.1cm)', value: 's10' },
        ],
    },
    {
        id: 6,
        groupId: 1000,
        name: 'Khapara Red Shoe',
        brand: "Khapara",
        tagline: 'The power of the shoe, perfected.',
        price: generateInteger(100),
        reviewCount: generateInteger(100000),
        averageRating: generateOneDecimalUnder5(),
        images: [
            { id: 1, href: "/shoe/redshoe/shoe (1).png", alt: 'AngledView' },
            { id: 2, href: "/shoe/redshoe/shoe (2).png", alt: 'BackView' },
            { id: 3, href: "/shoe/redshoe/shoe (3).png", alt: 'FrntView' },
            { id: 4, href: "/shoe/redshoe/shoe (4).png", alt: 'LeftSideView' },
            { id: 5, href: "/shoe/redshoe/shoe (5).png", alt: 'RightSideView' },
        ],
        color: { id: 6, name: 'Red', hex: 'bg-[#F05554]', selected: false },
        sizes: [
            { label: '5 (24.1cm)', value: 's5', selected: true },
            { label: '6 (24.8cm)', value: 's6' },
            { label: '7 (25.7cm)', value: 's7' },
            { label: '8 (26.5cm)', value: 's8' },
            { label: '9 (27.3cm)', value: 's9' },
            { label: '10 (28.1cm)', value: 's10' },
        ],
    },
    {
        id: 7,
        groupId: 2000,
        name: 'Premium Watch',
        brand: "Premium",
        tagline: 'Crafted for those who lead.',
        price: generateInteger(100),
        reviewCount: generateInteger(100000),
        averageRating: generateOneDecimalUnder5(),
        images: [
            { id: 1, href: "/watch/watch (1).png", alt: 'AngledView' },
            { id: 2, href: "/watch/watch (2).png", alt: 'FrontView' },
            { id: 3, href: "/watch/watch (3).png", alt: 'RightSide' },
        ],
        color: { id: 7, name: 'Sliver', hex: 'bg-[#C0C0C0]', selected: false },
        sizes: [
            { label: 'Small (160mm)', value: 'small' },
            { label: 'Medium (180mm)', value: 'medium', selected: true },
            { label: 'Large (200mm)', value: 'large' },
        ],
    },
    {
        id: 8,
        groupId: 3000,
        name: 'Impex Battery Fan',
        brand: "Impex",
        tagline: 'Cool comfort, anywhere you go.',
        price: generateInteger(100),
        reviewCount: generateInteger(100000),
        averageRating: generateOneDecimalUnder5(),
        images: [
            { id: 1, href: "/fan/batteryBlueFan/batteryFan (1).jpg", alt: 'FrontView' },
            { id: 2, href: "/fan/batteryBlueFan/batteryFan (2).jpg", alt: 'OtherView' },
            { id: 3, href: "/fan/batteryBlueFan/batteryFan (3).jpg", alt: 'OtherView' },
            { id: 4, href: "/fan/batteryBlueFan/batteryFan (4).jpg", alt: 'OtherView' },
            { id: 5, href: "/fan/batteryBlueFan/batteryFan (5).jpg", alt: 'OtherView' },
        ],
        color: { id: 8, name: 'Grey', hex: 'bg-[#8D8D8D]', selected: false },
        sizes: [],
    },
    {
        id: 9,
        groupId: 4000,
        name: 'Tanco Premium Ladies Purse',
        brand: "Tanco",
        tagline: 'Carry elegance, carry yourself.',
        price: generateInteger(100),
        reviewCount: generateInteger(100000),
        averageRating: generateOneDecimalUnder5(),
        images: [
            { id: 1, href: "/ladiesPurse/ladiesPurse (1).jpg", alt: 'FrontView' },
            { id: 2, href: "/ladiesPurse/ladiesPurse (2).jpg", alt: 'OtherView' },
            { id: 3, href: "/ladiesPurse/ladiesPurse (3).jpg", alt: 'OtherView' },
            { id: 4, href: "/ladiesPurse/ladiesPurse (4).jpg", alt: 'OtherView' },
        ],
        color: { id: 9, name: 'Grey', hex: 'bg-[#F4EEF0]', selected: false },
        sizes: [],
    },
    {
        id: 10,
        groupId: 5000,
        name: 'Kammee Black Neckband',
        brand: "Kammee",
        tagline: 'Style meets sound.',
        price: generateInteger(100),
        reviewCount: generateInteger(100000),
        averageRating: generateOneDecimalUnder5(),
        images: [
            { id: 1, href: "/nechband/blackNeckband/nechbandBlack (1).jpg", alt: 'FrontView' },
            { id: 2, href: "/nechband/nechband (1).jpg", alt: 'OtherView' },
            { id: 3, href: "/nechband/nechband (2).jpg", alt: 'OtherView' },
            { id: 4, href: "/nechband/blackNeckband/nechbandBlack (2).jpg", alt: 'FrontView' },
            { id: 5, href: "/nechband/blackNeckband/nechbandBlack (3).jpg", alt: 'FrontView' },
        ],
        color: { id: 10, name: 'Black', hex: 'bg-black', selected: true },
        sizes: [],
    },
    {
        id: 11,
        groupId: 5000,
        name: 'Kammee Sliver and Green Neckband',
        brand: "Kammee",
        tagline: 'Style meets sound.',
        price: generateInteger(100),
        reviewCount: generateInteger(100000),
        averageRating: generateOneDecimalUnder5(),
        images: [
            { id: 1, href: "/nechband/greenNeckBand/nechbandSliverAndGreen (1).jpg", alt: 'FrontView' },
            { id: 2, href: "/nechband/nechband (1).jpg", alt: 'OtherView' },
            { id: 3, href: "/nechband/nechband (2).jpg", alt: 'OtherView' },
            { id: 4, href: "/nechband/greenNeckBand/nechbandSliverAndGreen (2).jpg", alt: 'FrontView' },
            { id: 5, href: "/nechband/greenNeckBand/nechbandSliverAndGreen (3).jpg", alt: 'FrontView' },
            { id: 6, href: "/nechband/greenNeckBand/nechbandSliverAndGreen (4).jpg", alt: 'FrontView' },
            { id: 7, href: "/nechband/greenNeckBand/nechbandSliverAndGreen (5).jpg", alt: 'FrontView' },
        ],
        color: { id: 11, name: 'Green', hex: 'bg-[#BFD456]', selected: false },
        sizes: [],
    },
    {
        id: 12,
        groupId: 5000,
        name: 'Kammee Red Neckband',
        brand: "Kammee",
        tagline: 'Style meets sound.',
        price: generateInteger(100),
        reviewCount: generateInteger(100000),
        averageRating: generateOneDecimalUnder5(),
        images: [
            { id: 1, href: "/nechband/redNeckband/nechbandRed (1).jpg", alt: 'FrontView' },
            { id: 2, href: "/nechband/nechband (1).jpg", alt: 'OtherView' },
            { id: 3, href: "/nechband/nechband (2).jpg", alt: 'OtherView' },
            { id: 4, href: "/nechband/redNeckband/nechbandRed (2).jpg", alt: 'FrontView' },
            { id: 5, href: "/nechband/redNeckband/nechbandRed (3).jpg", alt: 'FrontView' },
        ],
        color: { id: 12, name: 'Red', hex: 'bg-[#FD1924]', selected: false },
        sizes: [],
    },
];

export const myWishlist = [
    {
        id: 1,
        productId: 1,
        name: "Khapara Black Shoe",
        price: 91,
        image: "/shoe/blackshoe/shoe (1).png",
        color: "Black",
        size: "s5"
    },
    {
        id: 2,
        productId: 8,
        name: "Impex Battery Fan",
        price: 21,
        image: "/fan/batteryBlueFan/batteryFan (1).jpg",
        color: "Grey",
        size: ""
    }
];

export const cartList = [
    {
        id: 1,
        productId: 1,
        quantity: 1,
        name: "Khapara Black Shoe",
        price: 6486,
        image: "/shoe/blackshoe/shoe (1).png",
        color: "Black",
        size: "s9",
    },
    {
        id: 2,
        productId: 12,
        color: "Red",
        size: "",
        quantity: 2,
        name: "Kammee Red Neckband",
        price: 5142,
        image: "/nechband/blackNeckband/nechbandBlack (1).jpg",
    },
    {
        id: 3,
        productId: 7,
        color: "Sliver",
        size: "medium",
        quantity: 4,
        name: 'Premium Watch',
        price: 150,
        image: "/watch/watch (1).png",
    },
    {
        id: 4,
        productId: 8,
        color: "Grey",
        size: "",
        quantity: 1,
        name: 'Impex Battery Fan',
        price: 600,
        image: "/fan/batteryBlueFan/batteryFan (1).jpg",
    },
    {
        id: 5,
        productId: 1,
        color: "Black",
        size: "s9",
        quantity: 1,
        name: "Khapara Black Shoe",
        price: 6486,
        image: "/shoe/blackshoe/shoe (1).png",
    },
    {
        id: 6,
        productId: 12,
        color: "Red",
        size: "",
        quantity: 2,
        name: "Kammee Red Neckband",
        price: 5142,
        image: "/nechband/blackNeckband/nechbandBlack (1).jpg",
    },
    {
        id: 7,
        productId: 7,
        color: "Sliver",
        size: "medium",
        quantity: 4,
        name: 'Premium Watch',
        price: 150,
        image: "/watch/watch (1).png",
    },
    {
        id: 8,
        productId: 8,
        color: "Grey",
        size: "",
        quantity: 1,
        name: 'Impex Battery Fan',
        price: 600,
        image: "/fan/batteryBlueFan/batteryFan (1).jpg",
    },
];

export const shippingInfo = [
    {
        id: 1,
        name: 'Alex Thompson',
        address: ['123 Maple Street, Apt 4B', 'Springfield, IL', '62704'],
        label: "home",
    },
    {
        id: 2,
        name: "Bava khan",
        address: [
            "10A/2, Thippu sulthan street",
            "Tirunelveli, Tamil nadu",
            "627453"
        ],
        nearByLandmark: "Veppamaram stop",
        emailId: "bava@gmail.com",
        telephoneNumber: "9988776655",
        label: "apartment",
    }
];

export const promoCodes = [
    { code: "FIRST20", percentage: 0.20 },
    { code: "SECOND10", percentage: 0.10 },
    { code: "DIWALI15", percentage: 0.15 }
];

export const paymentInfo = [
    {
        id: 1,
        cardNumber: "1234123412341234",
        cardHolderName: "John Deo",
        cardExpirationDate: "04/12",
        cardCVVNumber: "123",
        paymentType: "Credit Card"
    },
    {
        id: 2,
        cardNumber: "1234123412340000",
        cardHolderName: "John Deo",
        cardExpirationDate: "04/12",
        cardCVVNumber: "123",
        paymentType: "Credit Card"
    },
];

export const totalSummarys = [
    {
        id: "3e5b7884-c8c2-4cef-a07e-6c3d55421a7d",
        congineeDetail: {
            id: 1,
            name: "Alex Thompson",
            address: [
                "123 Maple Street, Apt 4B",
                "Springfield, IL, 62704",
                "United States"
            ]
        },
        shippingMethod: {
            id: "express",
            name: "Overnight Express",
            price: 100,
            eta: "Dec-06",
            isPopular: false
        },
        paymentMethod: {
            id: 1,
            paymentType: "COD"
        },
        items: [
            {
                id: 1,
                productId: 1,
                color: "Black",
                size: "s9",
                quantity: 1,
                name: "Khapara Black Shoe",
                price: 70,
                image: "/shoe/blackshoe/shoe (1).png"
            },
            {
                id: 2,
                productId: 12,
                color: "Red",
                size: "",
                quantity: 2,
                name: "Kammee Red Neckband",
                price: 62,
                image: "/nechband/blackNeckband/nechbandBlack (1).jpg"
            },
            {
                id: 3,
                productId: 7,
                color: "Sliver",
                size: "medium",
                quantity: 4,
                name: "Premium Watch",
                price: 14,
                image: "/watch/watch (1).png"
            },
            {
                id: 4,
                productId: 8,
                color: "Grey",
                size: "",
                quantity: 1,
                name: "Impex Battery Fan",
                price: 53,
                image: "/fan/batteryBlueFan/batteryFan (1).jpg"
            },
            {
                id: 5,
                productId: 1,
                color: "Black",
                size: "s9",
                quantity: 1,
                name: "Khapara Black Shoe",
                price: 11,
                image: "/shoe/blackshoe/shoe (1).png"
            },
            {
                id: 6,
                productId: 12,
                color: "Red",
                size: "",
                quantity: 2,
                name: "Kammee Red Neckband",
                price: 35,
                image: "/nechband/blackNeckband/nechbandBlack (1).jpg"
            },
            {
                id: 7,
                productId: 7,
                color: "Sliver",
                size: "medium",
                quantity: 4,
                name: "Premium Watch",
                price: 28,
                image: "/watch/watch (1).png"
            },
            {
                id: 8,
                productId: 8,
                color: "Grey",
                size: "",
                quantity: 1,
                name: "Impex Battery Fan",
                price: 81,
                image: "/fan/batteryBlueFan/batteryFan (1).jpg"
            }
        ],
        totalSummary: {
            subtotal: 577,
            deliveryFee: 100,
            marketPlaceFee: 5,
            total: 682,
        },
        deliveryStatus: {
            orderDate: "Dec-05",
            status: "Pending",
        },
    },
    {
        id: "2b772fc9-8fd2-45d9-9c45-936525037c19",
        congineeDetail: {
            id: 2,
            name: "Bava khan",
            address: [
                "10A/2, Thippu sulthan street",
                "Tirunelveli, Tamil nadu",
                "627453"
            ],
            nearByLandmark: "Veppamaram stop",
            emailId: "bava@gmail.com",
            telephoneNumber: "9988776655",
            label: "apartment"
        },
        shippingMethod: {
            id: "express",
            name: "Overnight Express",
            price: 100,
            eta: "Dec-08",
            isPopular: false
        },
        paymentMethod: {
            id: 1,
            cardNumber: "1234123412341234",
            cardHolderName: "John Deo",
            cardExpirationDate: "04/12",
            cardCVVNumber: "123",
            paymentType: "Credit Card"
        },
        items: [
            {
                id: 1,
                productId: 1,
                quantity: 1,
                name: "Khapara Black Shoe",
                price: 91,
                image: "/shoe/blackshoe/shoe (1).png",
                color: "Black",
                size: "s9"
            },
            {
                id: 2,
                productId: 12,
                color: "Red",
                size: "",
                quantity: 2,
                name: "Kammee Red Neckband",
                price: 40,
                image: "/nechband/blackNeckband/nechbandBlack (1).jpg"
            },
            {
                id: 3,
                productId: 7,
                color: "Sliver",
                size: "medium",
                quantity: 4,
                name: "Premium Watch",
                price: 76,
                image: "/watch/watch (1).png"
            },
            {
                id: 4,
                productId: 8,
                color: "Grey",
                size: "",
                quantity: 1,
                name: "Impex Battery Fan",
                price: 60,
                image: "/fan/batteryBlueFan/batteryFan (1).jpg"
            },
            {
                id: 5,
                productId: 1,
                color: "Black",
                size: "s9",
                quantity: 1,
                name: "Khapara Black Shoe",
                price: 88,
                image: "/shoe/blackshoe/shoe (1).png"
            },
            {
                id: 6,
                productId: 12,
                color: "Red",
                size: "",
                quantity: 2,
                name: "Kammee Red Neckband",
                price: 13,
                image: "/nechband/blackNeckband/nechbandBlack (1).jpg"
            },
            {
                id: 7,
                productId: 7,
                color: "Sliver",
                size: "medium",
                quantity: 4,
                name: "Premium Watch",
                price: 93,
                image: "/watch/watch (1).png"
            },
            {
                id: 8,
                productId: 8,
                color: "Grey",
                size: "",
                quantity: 1,
                name: "Impex Battery Fan",
                price: 51,
                image: "/fan/batteryBlueFan/batteryFan (1).jpg"
            }
        ],
        totalSummary: {
            subtotal: 1072,
            deliveryFee: 100,
            marketPlaceFee: 5,
            total: 1177
        }
    }
];

export const itemsStatus = [
    {
        id: "3e5b7884-c8c2-4cef-a07e-6c3d55421a7d",
        items: [
            {
                id: 1,
                productId: 1,
                color: "Black",
                size: "s9",
                quantity: 1,
                name: "Khapara Black Shoe",
                price: 70,
                image: "/shoe/blackshoe/shoe (1).png",
                status: "Pending",
                orderDate: "Dec-05",
                eta: "Dec-06",
                ata: "Jan-06",
            },
            {
                id: 2,
                productId: 12,
                color: "Red",
                size: "",
                quantity: 2,
                name: "Kammee Red Neckband",
                price: 62,
                image: "/nechband/blackNeckband/nechbandBlack (1).jpg",
                status: "Confirmed",
                orderDate: "Dec-05",
                eta: "Dec-06",
                ata: "Jan-06",
            },
            {
                id: 3,
                productId: 7,
                color: "Sliver",
                size: "medium",
                quantity: 4,
                name: "Premium Watch",
                price: 14,
                image: "/watch/watch (1).png",
                status: "Shipped",
                orderDate: "Dec-05",
                eta: "Dec-06",
                ata: "Jan-06",
            },
            {
                id: 4,
                productId: 8,
                color: "Grey",
                size: "",
                quantity: 1,
                name: "Impex Battery Fan",
                price: 53,
                image: "/fan/batteryBlueFan/batteryFan (1).jpg",
                status: "In Transit",
                orderDate: "Dec-05",
                eta: "Dec-06",
                ata: "Jan-06",
            },
            {
                id: 5,
                productId: 1,
                color: "Black",
                size: "s9",
                quantity: 1,
                name: "Khapara Black Shoe",
                price: 11,
                image: "/shoe/blackshoe/shoe (1).png",
                status: "Out for Delivery",
                orderDate: "Dec-05",
                eta: "Dec-06",
                ata: "Jan-06",
            },
            {
                id: 6,
                productId: 12,
                color: "Red",
                size: "",
                quantity: 2,
                name: "Kammee Red Neckband",
                price: 35,
                image: "/nechband/blackNeckband/nechbandBlack (1).jpg",
                status: "Delivered",
                orderDate: "Dec-05",
                eta: "Dec-06",
                ata: "Jan-06",
            },
            {
                id: 7,
                productId: 7,
                color: "Sliver",
                size: "medium",
                quantity: 4,
                name: "Premium Watch",
                price: 28,
                image: "/watch/watch (1).png",
                status: "Pending",
                orderDate: "Dec-05",
                eta: "Dec-06",
                ata: "Jan-06",
            },
            {
                id: 8,
                productId: 8,
                color: "Grey",
                size: "",
                quantity: 1,
                name: "Impex Battery Fan",
                price: 81,
                image: "/fan/batteryBlueFan/batteryFan (1).jpg",
                status: "Pending",
                orderDate: "Dec-05",
                eta: "Dec-06",
                ata: "Jan-06",
            }],
    }
];
